
"use client";

import { createContext, useContext, useState, ReactNode, useEffect, useCallback } from "react";

export type Language = "en" | "hi" | "ur" | "ar" | "tr" | "ms" | "fr";

const translations: Record<Language, Record<string, string>> = {
  en: {
    hero_headline: "Where Faith Meets Luxury",
    hero_subtext: "Explore a trusted marketplace of premium halal products — carefully curated and authentically verified for your peace of mind and values.",
    hero_cta: "Enter the Collection",
    nav_home: "Home",
    nav_products: "Products",
    nav_about: "About Us",
    nav_contact: "Contact",
    nav_admin_dashboard: "Admin Dashboard",
    nav_become_seller: "Become a Seller",
    nav_toggle_menu: "Toggle Menu",
    nav_change_language: "Change language",
    nav_search: "Search",
    nav_cart: "Shopping Cart",
    nav_user_menu: "User Menu",
    nav_my_account: "My Account",
    nav_profile: "Profile",
    nav_seller_dashboard: "Seller Dashboard",
    nav_store_settings: "Store Settings",
    nav_logout: "Log out",
    nav_login: "Login",
    lang_en: "English",
    lang_hi: "Hindi",
    lang_ur: "Urdu",
    lang_ar: "Arabic",
    lang_tr: "Turkish",
    lang_ms: "Malay",
    lang_fr: "French",
    footer_about: "About Us",
    footer_contact: "Contact",
    footer_terms: "Terms of Service",
    footer_privacy: "Privacy Policy",
    footer_rights: "All rights reserved.",
    recommendations_title: "Just For You",
    featured_products_title: "Featured Products",
    view_all_cta: "View All",
    product_halal_certified: "Halal Certified",
    product_add_to_cart: "Add to Cart",
    product_add_to_wishlist: "Add to Wishlist",
    product_remove_from_wishlist: "Remove from Wishlist",
    breadcrumb_home: "Home",
    about_us_breadcrumb: "About Us",
    about_our_story_title: "Our Story",
    about_our_story_desc: "Jalal Bazaar was born from a simple idea: to create a trusted, elegant, and convenient online space for consumers to find high-quality, authentic halal products.",
    about_image_alt: "Diverse team working together",
    about_commitment_title: "Committed to Authenticity and Faith",
    about_commitment_desc: "We bridge the gap between discerning consumers and ethical sellers who are proud of their halal-certified offerings.",
    about_mission_title: "Our Mission",
    about_mission_desc: "Our mission is to empower Muslim consumers and entrepreneurs. We meticulously vet every seller and product to ensure they meet strict halal standards, providing peace of mind with every purchase. We aim to be more than a marketplace; we want to be a cornerstone of the modern Muslim lifestyle, celebrating our heritage while embracing the future.",
    about_vision_title: "Our Vision",
    about_vision_desc: "We envision a world where every Muslim consumer has easy access to products that align with their values, no matter where they are. We strive to build a global community, fostering economic growth for halal businesses and creating a vibrant ecosystem of trust, quality, and shared faith-based principles.",
    cart_breadcrumb: "Shopping Cart",
    cart_title: "Your Cart",
    cart_description: "Review your items and proceed to checkout.",
    cart_empty_title: "Your cart is empty",
    cart_empty_desc: "Looks like you haven't added anything to your cart yet.",
    cart_start_shopping: "Start Shopping",
    cart_summary_title: "Order Summary",
    cart_summary_subtotal: "Subtotal",
    cart_summary_shipping: "Shipping",
    cart_summary_shipping_free: "Free",
    cart_summary_total: "Total",
    cart_proceed_to_checkout: "Proceed to Checkout",
    cart_remove_item: "Remove item",
    breadcrumb_cart: "Cart",
    breadcrumb_checkout: "Checkout",
    checkout_title: "Checkout",
    checkout_description: "Complete your purchase by providing the details below.",
    checkout_form_title: "Contact & Shipping",
    checkout_form_email: "Email Address",
    checkout_form_first_name: "First Name",
    checkout_form_last_name: "Last Name",
    checkout_form_address: "Address",
    checkout_form_city: "City",
    checkout_form_country: "Country",
    checkout_form_postal_code: "Postal Code",
    checkout_form_pay: "Pay",
    checkout_form_with_razorpay: "with Razorpay",
    checkout_form_processing: "Processing...",
    checkout_toast_empty_cart_title: "Your cart is empty",
    checkout_toast_empty_cart_desc: "Please add items to your cart before checking out.",
    checkout_razorpay_desc: "Your Halal Marketplace Purchase",
    checkout_toast_order_placed_title: "Order Placed!",
    checkout_toast_order_placed_desc: "Thank you for your purchase. Payment ID:",
    breadcrumb_contact: "Contact Us",
    contact_title: "Get In Touch",
    contact_description: "We'd love to hear from you. Whether you have a question about our products, sellers, or anything else, our team is ready to answer all your questions.",
    contact_form_first_name: "First name",
    contact_form_last_name: "Last name",
    contact_form_email: "Email",
    contact_form_message: "Message",
    contact_form_send: "Send Message",
    products_title: "Our Collection",
    products_description: "Explore our curated selection of authentic halal products.",
    products_search_placeholder: "Search products...",
    products_filter_placeholder: "Filter by category",
    products_all_categories: "All Categories",
    products_none_found_title: "No Products Found",
    products_none_found_desc: "Try adjusting your search or filters.",
    wishlist_title: "Wishlist",
    wishlist_description: "Your favorite items, all in one place.",
    wishlist_empty_title: "Your wishlist is empty",
    wishlist_empty_description: "Explore products and add your favorites here.",
    wishlist_discover_products: "Discover Products",
    toast_added_to_cart: "has been added to your cart.",
    toast_removed_from_cart: "Item has been removed from your cart.",
    toast_added_to_wishlist: "has been added to your wishlist.",
    toast_removed_from_wishlist: "has been removed from your wishlist.",
    seller_join_badge: "Start Your Journey",
    seller_join_title: "Become a Seller on Jalal Bazaar",
    seller_join_description: "Join a community of trusted vendors providing authentic halal products to a global audience. We provide the tools you need to grow your business.",
    seller_join_steps_title: "Start Selling in 3 Easy Steps",
    seller_join_steps_desc: "It's easy to get started. Just follow the steps below.",
    seller_join_step1_title: "Create Your Account",
    seller_join_step1_desc: "Fill out the registration form with your personal and store details. It only takes a few minutes.",
    seller_join_step2_title: "Upload Your Products",
    seller_join_step2_desc: "Once registered, you can access your seller dashboard to list your halal-certified products and set up your store profile.",
    seller_join_step3_title: "Submit for Review & Go Live",
    seller_join_step3_desc: "After you've set up your store, submit it for a final review. Our team will verify your certifications and products before you go live.",
    seller_join_already_account: "Already have an account?",
    seller_join_login_link: "Log In",
    seller_join_form_title: "Seller Registration",
    seller_join_form_desc: "Enter your details to create your seller account.",
    seller_form_first_name: "First Name",
    seller_form_last_name: "Last Name",
    seller_form_store_name: "Store Name",
    seller_form_email: "Email",
    seller_form_password: "Password",
    seller_form_business_details: "About Your Business",
    seller_form_bank_account: "Bank Account Number",
    seller_form_ifsc_code: "IFSC Code",
    seller_form_gst: "GST Number",
    seller_form_document: "Verification Document",
    seller_form_document_upload: "Click to upload document",
    seller_form_document_upload_desc: "(e.g., GST Certificate, Business License)",
    seller_form_document_selected: "Selected file:",
    seller_form_document_none: "No file selected.",
    seller_form_submit_button: "Create Account & Submit for Review",
    seller_form_submitting_button: "Submitting for review...",
    seller_form_first_name_placeholder: "John",
    seller_form_last_name_placeholder: "Doe",
    seller_form_store_name_placeholder: "My Awesome Store",
    seller_form_business_details_placeholder: "Describe your business, the products you sell, and your halal certification status...",
    seller_form_bank_account_placeholder: "Your bank account number",
    seller_form_ifsc_code_placeholder: "Your bank's IFSC code",
    seller_form_gst_placeholder: "GSTIN (optional)"
  },
  hi: {
    hero_headline: "आस्था विलासिता से मिलती है",
    hero_subtext: "प्रीमियम हलाल उत्पादों का एक विश्वसनीय बाज़ार खोजें - आपकी मन की शांति और मूल्यों के लिए सावधानीपूर्वक क्यूरेट और प्रमाणित रूप से सत्यापित।",
    hero_cta: "संग्रह में प्रवेश करें",
    nav_home: "होम",
    nav_products: "उत्पाद",
    nav_about: "हमारे बारे में",
    nav_contact: "संपर्क",
    nav_admin_dashboard: "एडमिन डैशबोर्ड",
    nav_become_seller: "विक्रेता बनें",
    nav_toggle_menu: "मेनू टॉगल करें",
    nav_change_language: "भाषा बदलें",
    nav_search: "खोज",
    nav_cart: "शॉपिंग कार्ट",
    nav_user_menu: "उपयोगकर्ता मेनू",
    nav_my_account: "मेरा खाता",
    nav_profile: "प्रोफ़ाइल",
    nav_seller_dashboard: "विक्रेता डैशबोर्ड",
    nav_store_settings: "स्टोर सेटिंग्स",
    nav_logout: "लॉग आउट",
    nav_login: "लॉग इन करें",
    lang_en: "अंग्रेजी",
    lang_hi: "हिंदी",
    lang_ur: "उर्दू",
    lang_ar: "अरबी",
    lang_tr: "तुर्की",
    lang_ms: "मलय",
    lang_fr: "फ्रेंच",
    footer_about: "हमारे बारे में",
    footer_contact: "संपर्क",
    footer_terms: "सेवा की शर्तें",
    footer_privacy: "गोपनीयता नीति",
    footer_rights: "सर्वाधिकार सुरक्षित।",
    recommendations_title: "केवल आपके लिए",
    featured_products_title: "विशेष रुप से प्रदर्शित उत्पाद",
    view_all_cta: "सभी देखें",
    product_halal_certified: "हलाल प्रमाणित",
    product_add_to_cart: "कार्ट में डालें",
    product_add_to_wishlist: "इच्छा-सूची में जोड़ें",
    product_remove_from_wishlist: "इच्छा-सूची से हटाएं",
    breadcrumb_home: "होम",
    about_us_breadcrumb: "हमारे بارے میں",
    about_our_story_title: "हमारी कहानी",
    about_our_story_desc: "जलाल बाज़ार का जन्म एक साधारण विचार से हुआ: उपभोक्ताओं को उच्च-गुणवत्ता, प्रामाणिक हलाल उत्पाद खोजने के लिए एक विश्वसनीय, सुंदर और सुविधाजनक ऑनलाइन स्थान बनाना।",
    about_image_alt: "विविध टीम एक साथ काम कर रही है",
    about_commitment_title: "प्रामाणिकता और आस्था के प्रति प्रतिबद्ध",
    about_commitment_desc: "हम समझदार उपभोक्ताओं और नैतिक विक्रेताओं के बीच की खाई को पाटते हैं जो अपनी हलाल-प्रमाणित पेशकशों पर गर्व करते हैं।",
    about_mission_title: "हमारा विशेष कार्य",
    about_mission_desc: "हमारा मिशन मुस्लिम उपभोक्ताओं और उद्यमियों को सशक्त बनाना है। हम यह सुनिश्चित करने के लिए हर विक्रेता और उत्पाद की सावधानीपूर्वक जांच करते हैं कि वे सख्त हलाल मानकों को पूरा करते हैं, जिससे हर खरीद के साथ मानसिक शांति मिलती है। हमारा लक्ष्य एक बाज़ार से कहीं ज़्यादा होना है; हम आधुनिक मुस्लिम जीवन शैली का एक आधार बनना चाहते हैं, अपनी विरासत का जश्न मनाते हुए भविष्य को अपनाते हैं।",
    about_vision_title: "हमारा नज़रिया",
    about_vision_desc: "हम एक ऐसी दुनिया की कल्पना करते हैं जहां हर मुस्लिम उपभोक्ता को उन उत्पादों तक आसान पहुंच हो जो उनके मूल्यों के अनुरूप हों, चाहे वे कहीं भी हों। हम एक वैश्विक समुदाय बनाने, हलाल व्यवसायों के लिए आर्थिक विकास को बढ़ावा देने और विश्वास, गुणवत्ता और साझा आस्था-आधारित सिद्धांतों का एक जीवंत पारिस्थितिकी तंत्र बनाने का प्रयास करते हैं।",
    cart_breadcrumb: "शॉपिंग कार्ट",
    cart_title: "आपकी गाड़ी",
    cart_description: "अपने आइटम की समीक्षा करें और चेकआउट के लिए आगे बढ़ें।",
    cart_empty_title: "आपकी गाड़ी खाली है",
    cart_empty_desc: "लगता है आपने अभी तक अपनी कार्ट में कुछ भी नहीं जोड़ा है।",
    cart_start_shopping: "खरीदारी शुरू करें",
    cart_summary_title: "आदेश सारांश",
    cart_summary_subtotal: "उप-योग",
    cart_summary_shipping: "शिपिंग",
    cart_summary_shipping_free: "नि: शुल्क",
    cart_summary_total: "कुल",
    cart_proceed_to_checkout: "चेकआउट करने के लिए आगे बढ़ें",
    cart_remove_item: "आइटम निकालें",
    breadcrumb_cart: "कार्ट",
    breadcrumb_checkout: "चेक आउट",
    checkout_title: "चेक आउट",
    checkout_description: "नीचे दिए गए विवरण प्रदान करके अपनी खरीद पूरी करें।",
    checkout_form_title: "संपर्क और शिपिंग",
    checkout_form_email: "ईमेल पता",
    checkout_form_first_name: "पहला नाम",
    checkout_form_last_name: "अंतिम नाम",
    checkout_form_address: "पता",
    checkout_form_city: "शहर",
    checkout_form_country: "देश",
    checkout_form_postal_code: "डाक कोड",
    checkout_form_pay: "भुगतान करें",
    checkout_form_with_razorpay: "रेजरपे के साथ",
    checkout_form_processing: "प्रसंस्करण हो रहा है...",
    checkout_toast_empty_cart_title: "आपकी गाड़ी खाली है",
    checkout_toast_empty_cart_desc: "कृपया चेक आउट करने से पहले अपनी कार्ट में आइटम जोड़ें।",
    checkout_razorpay_desc: "आपकी हलाल मार्केटप्लेस खरीद",
    checkout_toast_order_placed_title: "आदेश दिया गया!",
    checkout_toast_order_placed_desc: "आपकी खरीद के लिए धन्यवाद। भुगतान आईडी:",
    breadcrumb_contact: "संपर्क करें",
    contact_title: "संपर्क में रहो",
    contact_description: "हमें आपसे सुनकर खुशी होगी। चाहे आपके पास हमारे उत्पादों, विक्रेताओं, या किसी और चीज़ के बारे में कोई प्रश्न हो, हमारी टीम आपके सभी सवालों का जवाब देने के लिए तैयार है।",
    contact_form_first_name: "पहला नाम",
    contact_form_last_name: "अंतिम नाम",
    contact_form_email: "ईमेल",
    contact_form_message: "संदेश",
    contact_form_send: "संदेश भेजो",
    products_title: "हमारा संग्रह",
    products_description: "प्रामाणिक हलाल उत्पादों के हमारे क्यूरेटेड चयन का अन्वेषण करें।",
    products_search_placeholder: "उत्पाद खोजें...",
    products_filter_placeholder: "श्रेणी के अनुसार फ़िल्टर करें",
    products_all_categories: "सभी श्रेणियाँ",
    products_none_found_title: "कोई उत्पाद नहीं मिला",
    products_none_found_desc: "अपनी खोज या फ़िल्टर समायोजित करने का प्रयास करें।",
    wishlist_title: "इच्छा-सूची",
    wishlist_description: "आपकी पसंदीदा वस्तुएँ, सब एक ही स्थान पर।",
    wishlist_empty_title: "आपकी इच्छा सूची खाली है",
    wishlist_empty_description: "उत्पादों का अन्वेषण करें और अपने पसंदीदा यहाँ जोड़ें।",
    wishlist_discover_products: "उत्पादों की खोज करें",
    toast_added_to_cart: "आपकी कार्ट में जोड़ दिया गया है।",
    toast_removed_from_cart: "आइटम आपकी कार्ट से हटा दिया गया है।",
    toast_added_to_wishlist: "आपकी इच्छा-सूची में जोड़ दिया गया है।",
    toast_removed_from_wishlist: "आपकी इच्छा-सूची से हटा दिया गया है।",
    seller_join_badge: "अपनी यात्रा शुरू करें",
    seller_join_title: "जलाल बाज़ार पर विक्रेता बनें",
    seller_join_description: "विश्वसनीय विक्रेताओं के एक समुदाय में शामिल हों जो वैश्विक दर्शकों को प्रामाणिक हलाल उत्पाद प्रदान करते हैं। हम आपको अपना व्यवसाय बढ़ाने के लिए आवश्यक उपकरण प्रदान करते हैं।",
    seller_join_steps_title: "3 आसान चरणों में बेचना शुरू करें",
    seller_join_steps_desc: "शुरुआत करना आसान है। बस नीचे दिए गए चरणों का पालन करें।",
    seller_join_step1_title: "अपना खाता बनाएं",
    seller_join_step1_desc: "अपने व्यक्तिगत और स्टोर विवरण के साथ पंजीकरण फॉर्म भरें। इसमें केवल कुछ मिनट लगते हैं।",
    seller_join_step2_title: "अपने उत्पाद अपलोड करें",
    seller_join_step2_desc: "एक बार पंजीकृत होने के बाद, आप अपने हलाल-प्रमाणित उत्पादों को सूचीबद्ध करने और अपनी स्टोर प्रोफ़ाइल सेट करने के लिए अपने विक्रेता डैशबोर्ड तक पहुँच सकते हैं।",
    seller_join_step3_title: "समीक्षा के लिए सबमिट करें और लाइव जाएं",
    seller_join_step3_desc: "अपना स्टोर स्थापित करने के बाद, इसे अंतिम समीक्षा के लिए सबमिट करें। हमारी टीम आपके प्रमाणपत्रों और उत्पादों को लाइव होने से पहले सत्यापित करेगी।",
    seller_join_already_account: "पहले से ही एक खाता हैं?",
    seller_join_login_link: "लॉग इन करें",
    seller_join_form_title: "विक्रेता पंजीकरण",
    seller_join_form_desc: "अपना विक्रेता खाता बनाने के लिए अपना विवरण दर्ज करें।",
    seller_form_first_name: "पहला नाम",
    seller_form_last_name: "अंतिम नाम",
    seller_form_store_name: "स्टोर का नाम",
    seller_form_email: "ईमेल",
    seller_form_password: "पासवर्ड",
    seller_form_business_details: "आपके व्यवसाय के बारे में",
    seller_form_bank_account: "बैंक खाता संख्या",
    seller_form_ifsc_code: "आईएफएससी कोड",
    seller_form_gst: "जीएसटी नंबर",
    seller_form_document: "सत्यापन दस्तावेज़",
    seller_form_document_upload: "दस्तावेज़ अपलोड करने के लिए क्लिक करें",
    seller_form_document_upload_desc: "(उदाहरण, जीएसटी प्रमाणपत्र, व्यापार लाइसेंस)",
    seller_form_document_selected: "चयनित फ़ाइल:",
    seller_form_document_none: "कोई फ़ाइल नहीं चुनी गई।",
    seller_form_submit_button: "खाता बनाएं और समीक्षा के लिए सबमिट करें",
    seller_form_submitting_button: "समीक्षा के लिए सबमिट किया जा रहा है...",
    seller_form_first_name_placeholder: "जॉन",
    seller_form_last_name_placeholder: "डो",
    seller_form_store_name_placeholder: "मेरा अद्भुत स्टोर",
    seller_form_business_details_placeholder: "अपने व्यवसाय, आपके द्वारा बेचे जाने वाले उत्पादों और अपनी हलाल प्रमाणीकरण स्थिति का वर्णन करें...",
    seller_form_bank_account_placeholder: "आपका बैंक खाता नंबर",
    seller_form_ifsc_code_placeholder: "आपके बैंक का IFSC कोड",
    seller_form_gst_placeholder: "जीएसटीआईएन (वैकल्पिक)"
  },
  ur: {
    hero_headline: "جہاں ایمان عیش و عشرت سے ملتا ہے۔",
    hero_subtext: "پریمیم حلال مصنوعات کا ایک قابل اعتماد بازار دریافت کریں — آپ کے ذہنی سکون اور اقدار کے لیے احتیاط سے تیار اور مستند طور پر تصدیق شدہ۔",
    hero_cta: "مجموعہ میں داخل ہوں۔",
    nav_home: "گھر",
    nav_products: "مصنوعات",
    nav_about: "ہمارے بارے میں",
    nav_contact: "رابطہ کریں۔",
    nav_admin_dashboard: "ایڈمن ڈیش بورڈ",
    nav_become_seller: "بیچنے والے بنیں۔",
    nav_toggle_menu: "مینو کو ٹوگل کریں۔",
    nav_change_language: "زبان تبدیل کریں",
    nav_search: "تلاش کریں۔",
    nav_cart: "خریداری کی ٹوکری",
    nav_user_menu: "صارف مینو",
    nav_my_account: "میرا اکاونٹ",
    nav_profile: "پروفائل",
    nav_seller_dashboard: "بیچنے والے کا ڈیش بورڈ",
    nav_store_settings: "اسٹور کی ترتیبات",
    nav_logout: "لاگ آوٹ",
    nav_login: "لاگ ان کریں",
    lang_en: "انگریزی",
    lang_hi: "ہندی",
    lang_ur: "اردو",
    lang_ar: "عربی",
    lang_tr: "ترکی",
    lang_ms: "مالائی",
    lang_fr: "فرانسیسی",
    footer_about: "ہمارے بارے میں",
    footer_contact: "رابطہ کریں۔",
    footer_terms: "سروس کی شرائط",
    footer_privacy: "رازداری کی پالیسی",
    footer_rights: "جملہ حقوق محفوظ ہیں.",
    recommendations_title: "صرف آپ کے لیے",
    featured_products_title: "نمایاں مصنوعات",
    view_all_cta: "سب دیکھیں",
    product_halal_certified: "حلال مصدقہ",
    product_add_to_cart: "ٹوکری میں شامل کریں",
    product_add_to_wishlist: "خواہش کی فہرست میں شامل کرنا",
    product_remove_from_wishlist: "خواہش کی فہرست سے ہٹا دیں۔",
    breadcrumb_home: "گھر",
    about_us_breadcrumb: "ہمارے بارے میں",
    about_our_story_title: "ہماری کہانی",
    about_our_story_desc: "جلال بازار کا জন্ম ایک سادہ خیال سے ہوا: صارفین کو اعلیٰ معیار کی، مستند حلال مصنوعات تلاش کرنے کے لیے ایک قابل اعتماد، خوبصورت اور آسان آن لائن جگہ بنانا۔",
    about_image_alt: "متنوع ٹیم مل کر کام کر رہی ہے۔",
    about_commitment_title: "مستندی اور ایمان کے پابند",
    about_commitment_desc: "ہم سمجھدار صارفین اور اخلاقی فروخت کنندگان کے درمیان فرق کو پر کرتے ہیں جو اپنی حلال مصدقہ پیشکشوں پر فخر کرتے ہیں۔",
    about_mission_title: "ہمارا مقصد",
    about_mission_desc: "ہمارا مشن مسلم صارفین اور کاروباریوں کو بااختیار بنانا ہے۔ ہم ہر فروخت کنندہ اور پروڈکٹ کی باریک بینی سے جانچ پڑتال کرتے ہیں تاکہ یہ یقینی بنایا جا سکے کہ وہ سخت حلال معیارات پر پورا اترتے ہیں، ہر خریداری کے ساتھ ذہنی سکون فراہم کرتے ہیں۔ ہمارا مقصد ایک بازار سے زیادہ ہونا ہے۔ ہم جدید مسلم طرز زندگی کا سنگ بنیاد بننا چاہتے ہیں، اپنی وراثت کا جشن مناتے ہوئے مستقبل کو گلے لگاتے ہیں۔",
    about_vision_title: "ہمارا وژن",
    about_vision_desc: "ہم ایک ایسی دنیا کا تصور کرتے ہیں جہاں ہر مسلمان صارف کو اپنی اقدار کے مطابق مصنوعات تک آسانی سے رسائی حاصل ہو، چاہے وہ کہیں بھی ہوں۔ ہم ایک عالمی برادری کی تعمیر، حلال کاروباروں کے لیے اقتصادی ترقی کو فروغ دینے، اور اعتماد، معیار اور مشترکہ ایمانی اصولوں کا ایک متحرک ماحولیاتی نظام بنانے کی کوشش کرتے ہیں۔",
    cart_breadcrumb: "خریداری کی ٹوکری",
    cart_title: "آپ کی ٹوکری",
    cart_description: "اپنی اشیاء کا جائزہ لیں اور چیک آؤٹ کے لیے آگے بڑھیں۔",
    cart_empty_title: "آپ کی ٹوکری خالی ہے۔",
    cart_empty_desc: "ایسا لگتا ہے کہ آپ نے ابھی تک اپنی ٹوکری میں کچھ شامل نہیں کیا ہے۔",
    cart_start_shopping: "خریداری شروع کریں۔",
    cart_summary_title: "آرڈر کا خلاصہ",
    cart_summary_subtotal: "ذیلی کل",
    cart_summary_shipping: "شپنگ",
    cart_summary_shipping_free: "مفت",
    cart_summary_total: "کل",
    cart_proceed_to_checkout: "چیک آؤٹ کے لیے آگے بڑھیں۔",
    cart_remove_item: "آئٹم کو ہٹا دیں۔",
    breadcrumb_cart: "ٹوکری",
    breadcrumb_checkout: "چیک آؤٹ",
    checkout_title: "چیک آؤٹ",
    checkout_description: "نیچے دی گئی تفصیلات فراہم کرکے اپنی خریداری مکمل کریں۔",
    checkout_form_title: "رابطہ اور شپنگ",
    checkout_form_email: "ای میل اڈریس",
    checkout_form_first_name: "پہلا نام",
    checkout_form_last_name: "آخری نام",
    checkout_form_address: "پتہ",
    checkout_form_city: "شہر",
    checkout_form_country: "ملک",
    checkout_form_postal_code: "ڈاک کوڈ",
    checkout_form_pay: "ادائیگی کریں۔",
    checkout_form_with_razorpay: "Razorpay کے ساتھ",
    checkout_form_processing: "کارروائی ہو رہی ہے...",
    checkout_toast_empty_cart_title: "آپ کی ٹوکری خالی ہے۔",
    checkout_toast_empty_cart_desc: "براہ کرم چیک آؤٹ کرنے سے پہلے اپنی ٹوکری میں اشیاء شامل کریں۔",
    checkout_razorpay_desc: "آپ کی حلال مارکیٹ پلیس کی خریداری",
    checkout_toast_order_placed_title: "آرڈر دے دیا گیا!",
    checkout_toast_order_placed_desc: "آپ کی خریداری کے لئے آپ کا شکریہ. ادائیگی کی شناخت:",
    breadcrumb_contact: "ہم سے رابطہ کریں۔",
    contact_title: "رابطے میں رہنا",
    contact_description: "ہم آپ سے سننا پسند کریں گے۔ چاہے آپ کے پاس ہماری مصنوعات، فروخت کنندگان، یا کسی اور چیز کے بارے میں کوئی سوال ہو، ہماری ٹیم آپ کے تمام سوالات کا جواب دینے کے لیے تیار ہے۔",
    contact_form_first_name: "پہلا نام",
    contact_form_last_name: "آخری نام",
    contact_form_email: "ای میل",
    contact_form_message: "پیغام",
    contact_form_send: "پیغام بھیجیں",
    products_title: "ہمارا مجموعہ",
    products_description: "مستند حلال مصنوعات کے ہمارے منتخب کردہ انتخاب کو دریافت کریں۔",
    products_search_placeholder: "مصنوعات تلاش کریں...",
    products_filter_placeholder: "زمرہ کے لحاظ سے فلٹر کریں۔",
    products_all_categories: "تمام زمرے",
    products_none_found_title: "کوئی پروڈکٹ نہیں ملا",
    products_none_found_desc: "اپنی تلاش یا فلٹرز کو ایڈجسٹ کرنے کی کوشش کریں۔",
    wishlist_title: "خواہش کی فہرست",
    wishlist_description: "آپ کی پسندیدہ اشیاء، سب ایک جگہ پر۔",
    wishlist_empty_title: "آپ کی خواہش کی فہرست خالی ہے۔",
    wishlist_empty_description: "مصنوعات دریافت کریں اور اپنی پسندیدہ چیزیں یہاں شامل کریں۔",
    wishlist_discover_products: "مصنوعات دریافت کریں۔",
    toast_added_to_cart: "آپ کی ٹوکری میں شامل کر دیا گیا ہے۔",
    toast_removed_from_cart: "آئٹم آپ کی ٹوکری سے ہٹا دیا گیا ہے۔",
    toast_added_to_wishlist: "آپ کی خواہش کی فہرست میں شامل کر دیا گیا ہے۔",
    toast_removed_from_wishlist: "آپ کی خواہش کی فہرست سے ہٹا دیا گیا ہے۔",
    seller_join_badge: "اپنا سفر شروع کریں۔",
    seller_join_title: "جلال بازار پر بیچنے والے بنیں۔",
    seller_join_description: "قابل اعتماد دکانداروں کی کمیونٹی میں شامل ہوں جو عالمی سامعین کو مستند حلال مصنوعات فراہم کرتے ہیں۔ ہم آپ کو اپنے کاروبار کو بڑھانے کے لیے درکار اوزار فراہم کرتے ہیں۔",
    seller_join_steps_title: "3 آسان مراحل میں فروخت شروع کریں۔",
    seller_join_steps_desc: "شروع کرنا آسان ہے۔ بس نیچے دیے گئے اقدامات پر عمل کریں۔",
    seller_join_step1_title: "اپنا اکاؤنٹ بنائیں۔",
    seller_join_step1_desc: "رجسٹریشن فارم کو اپنی ذاتی اور اسٹور کی تفصیلات سے پُر کریں۔ اس میں صرف چند منٹ لگتے ہیں۔",
    seller_join_step2_title: "اپنی مصنوعات اپ لوڈ کریں۔",
    seller_join_step2_desc: "ایک بار رجسٹر ہونے کے بعد، آپ اپنی حلال مصدقہ مصنوعات کی فہرست بنانے اور اپنے اسٹور پروفائل کو ترتیب دینے کے لیے اپنے بیچنے والے کے ڈیش بورڈ تک رسائی حاصل کر سکتے ہیں۔",
    seller_join_step3_title: "جائزہ کے لیے جمع کروائیں اور لائیو جائیں۔",
    seller_join_step3_desc: "اپنے اسٹور کو ترتیب دینے کے بعد، اسے حتمی جائزے کے لیے جمع کروائیں۔ ہماری ٹیم آپ کے سرٹیفیکیشنز اور مصنوعات کی تصدیق کرے گی اس سے پہلے کہ آپ لائیو ہوں۔",
    seller_join_already_account: "پہلے سے ہی ایک اکاؤنٹ ہے؟",
    seller_join_login_link: "لاگ ان کریں",
    seller_join_form_title: "بیچنے والے کی رجسٹریشن",
    seller_join_form_desc: "اپنا بیچنے والا اکاؤنٹ بنانے کے لیے اپنی تفصیلات درج کریں۔",
    seller_form_first_name: "پہلا نام",
    seller_form_last_name: "آخری نام",
    seller_form_store_name: "اسٹور کا نام",
    seller_form_email: "ای میل",
    seller_form_password: "پاس ورڈ",
    seller_form_business_details: "اپنے کاروبار کے بارے میں",
    seller_form_bank_account: "بینک اکاؤنٹ نمبر",
    seller_form_ifsc_code: "IFSC کوڈ",
    seller_form_gst: "GST نمبر",
    seller_form_document: "تصدیقی دستاویز",
    seller_form_document_upload: "دستاویز اپ لوڈ کرنے کے لیے کلک کریں۔",
    seller_form_document_upload_desc: "(مثلاً، جی ایس ٹی سرٹیفکیٹ، کاروباری لائسنس)",
    seller_form_document_selected: "منتخب فائل:",
    seller_form_document_none: "کوئی فائل منتخب نہیں کی گئی۔",
    seller_form_submit_button: "اکاؤنٹ بنائیں اور جائزہ کے لیے جمع کروائیں۔",
    seller_form_submitting_button: "جائزہ کے لیے جمع کرایا جا رہا ہے...",
    seller_form_first_name_placeholder: "جان",
    seller_form_last_name_placeholder: "ڈو",
    seller_form_store_name_placeholder: "میرا زبردست اسٹور",
    seller_form_business_details_placeholder: "اپنے کاروبار، آپ جو مصنوعات فروخت کرتے ہیں، اور اپنی حلال سرٹیفیکیشن کی حیثیت بیان کریں...",
    seller_form_bank_account_placeholder: "آپ کا بینک اکاؤنٹ نمبر",
    seller_form_ifsc_code_placeholder: "آپ کے بینک کا IFSC کوڈ",
    seller_form_gst_placeholder: "جی ایس ٹی آئی این (اختیاری)"
  },
  ar: {
    hero_headline: "حيث يلتقي الإيمان بالفخامة",
    hero_subtext: "استكشف سوقًا موثوقًا به للمنتجات الحلال المتميزة - المنسقة بعناية والمتحقق منها بشكل أصلي من أجل راحة بالك وقيمك.",
    hero_cta: "أدخل المجموعة",
    nav_home: "الرئيسية",
    nav_products: "المنتجات",
    nav_about: "معلومات عنا",
    nav_contact: "اتصل",
    nav_admin_dashboard: "لوحة تحكم المسؤول",
    nav_become_seller: "كن بائعا",
    nav_toggle_menu: "تبديل القائمة",
    nav_change_language: "تغيير اللغة",
    nav_search: "بحث",
    nav_cart: "عربة التسوق",
    nav_user_menu: "قائمة المستخدم",
    nav_my_account: "حسابي",
    nav_profile: "الملف الشخصي",
    nav_seller_dashboard: "لوحة تحكم البائع",
    nav_store_settings: "إعدادات المتجر",
    nav_logout: "تسجيل الخروج",
    nav_login: "تسجيل الدخول",
    lang_en: "الإنجليزية",
    lang_hi: "الهندية",
    lang_ur: "الأردية",
    lang_ar: "عربي",
    lang_tr: "اللغة التركية",
    lang_ms: "لغة الملايو",
    lang_fr: "فرنسي",
    footer_about: "معلومات عنا",
    footer_contact: "اتصل",
    footer_terms: "شروط الخدمة",
    footer_privacy: "سياسة الخصوصية",
    footer_rights: "كل الحقوق محفوظة.",
    recommendations_title: "فقط لأجلك",
    featured_products_title: "منتجات مميزة",
    view_all_cta: "عرض الكل",
    product_halal_certified: "حلال معتمد",
    product_add_to_cart: "أضف إلى السلة",
    product_add_to_wishlist: "أضف إلى قائمة الامنيات",
    product_remove_from_wishlist: "إزالة من قائمة الرغبات",
    breadcrumb_home: "الرئيسية",
    about_us_breadcrumb: "معلومات عنا",
    about_our_story_title: "قصتنا",
    about_our_story_desc: "وُلد جلال بازار من فكرة بسيطة: إنشاء مساحة إلكترونية موثوقة وأنيقة ومريحة للمستهلكين للعثور على منتجات حلال عالية الجودة وأصلية.",
    about_image_alt: "فريق متنوع يعمل معًا",
    about_commitment_title: "ملتزمون بالأصالة والإيمان",
    about_commitment_desc: "نحن نسد الفجوة بين المستهلكين المميزين والبائعين الأخلاقيين الذين يفخرون بعروضهم المعتمدة كمنتجات حلال.",
    about_mission_title: "مهمتنا",
    about_mission_desc: "مهمتنا هي تمكين المستهلكين ورجال الأعمال المسلمين. نحن نفحص بدقة كل بائع ومنتج للتأكد من استيفائهم لمعايير الحلال الصارمة، مما يوفر راحة البال مع كل عملية شراء. نهدف إلى أن نكون أكثر من مجرد سوق؛ نريد أن نكون حجر الزاوية في نمط الحياة الإسلامي الحديث، نحتفل بتراثنا مع احتضان المستقبل.",
    about_vision_title: "رؤيتنا",
    about_vision_desc: "نتصور عالمًا يتمتع فيه كل مستهلك مسلم بوصول سهل إلى المنتجات التي تتوافق مع قيمه، بغض النظر عن مكان وجوده. نحن نسعى جاهدين لبناء مجتمع عالمي، وتعزيز النمو الاقتصادي للشركات الحلال، وإنشاء نظام بيئي نابض بالحياة من الثقة والجودة والمبادئ المشتركة القائمة على الإيمان.",
    cart_breadcrumb: "عربة التسوق",
    cart_title: "عربة التسوق الخاصة بك",
    cart_description: "راجع أغراضك وتابع عملية الدفع.",
    cart_empty_title: "عربة التسوق فارغة",
    cart_empty_desc: "يبدو أنك لم تضف أي شيء إلى عربة التسوق الخاصة بك بعد.",
    cart_start_shopping: "ابدأ التسوق",
    cart_summary_title: "ملخص الطلب",
    cart_summary_subtotal: "المجموع الفرعي",
    cart_summary_shipping: "شحن",
    cart_summary_shipping_free: "مجانا",
    cart_summary_total: "المجموع",
    cart_proceed_to_checkout: "باشر لإنهاء الدفع",
    cart_remove_item: "إزالة البند",
    breadcrumb_cart: "عربة التسوق",
    breadcrumb_checkout: "الدفع",
    checkout_title: "الدفع",
    checkout_description: "أكمل عملية الشراء من خلال تقديم التفاصيل أدناه.",
    checkout_form_title: "الاتصال والشحن",
    checkout_form_email: "عنوان البريد الإلكتروني",
    checkout_form_first_name: "الاسم الأول",
    checkout_form_last_name: "اسم العائلة",
    checkout_form_address: "عنوان",
    checkout_form_city: "مدينة",
    checkout_form_country: "دولة",
    checkout_form_postal_code: "الرمز البريدي",
    checkout_form_pay: "ادفع",
    checkout_form_with_razorpay: "مع ريزورباي",
    checkout_form_processing: "معالجة...",
    checkout_toast_empty_cart_title: "عربة التسوق فارغة",
    checkout_toast_empty_cart_desc: "يرجى إضافة عناصر إلى سلة التسوق الخاصة بك قبل الخروج.",
    checkout_razorpay_desc: "شراء سوق الحلال الخاص بك",
    checkout_toast_order_placed_title: "تم الطلب!",
    checkout_toast_order_placed_desc: "شكرا لك على الشراء. معرف الدفع:",
    breadcrumb_contact: "اتصل بنا",
    contact_title: "ابقى على تواصل",
    contact_description: "يسعدنا أن نسمع منك. سواء كان لديك سؤال حول منتجاتنا أو البائعين أو أي شيء آخر ، فإن فريقنا مستعد للإجابة على جميع أسئلتك.",
    contact_form_first_name: "الاسم الأول",
    contact_form_last_name: "اسم العائلة",
    contact_form_email: "البريد الإلكتروني",
    contact_form_message: "رسالة",
    contact_form_send: "إرسال رسالة",
    products_title: "مجموعتنا",
    products_description: "اكتشف مجموعتنا المختارة من المنتجات الحلال الأصيلة.",
    products_search_placeholder: "البحث عن المنتجات...",
    products_filter_placeholder: "التصفية حسب الفئة",
    products_all_categories: "جميع الفئات",
    products_none_found_title: "لم يتم العثور على منتجات",
    products_none_found_desc: "حاول تعديل البحث أو المرشحات.",
    wishlist_title: "قائمة الرغبات",
    wishlist_description: "العناصر المفضلة لديك ، كلها في مكان واحد.",
    wishlist_empty_title: "قائمة أمنياتك فارغة",
    wishlist_empty_description: "اكتشف المنتجات وأضف مفضلاتك هنا.",
    wishlist_discover_products: "اكتشف المنتجات",
    toast_added_to_cart: "تمت إضافته إلى سلة التسوق الخاصة بك.",
    toast_removed_from_cart: "تمت إزالة العنصر من سلة التسوق الخاصة بك.",
    toast_added_to_wishlist: "تمت إضافته إلى قائمة أمنياتك.",
    toast_removed_from_wishlist: "تمت إزالته من قائمة أمنياتك.",
    seller_join_badge: "ابدأ رحلتك",
    seller_join_title: "كن بائعًا في جلال بازار",
    seller_join_description: "انضم إلى مجتمع من البائعين الموثوق بهم الذين يقدمون منتجات حلال أصلية لجمهور عالمي. نحن نقدم الأدوات التي تحتاجها لتنمية عملك.",
    seller_join_steps_title: "ابدأ البيع في 3 خطوات سهلة",
    seller_join_steps_desc: "من السهل البدء. ما عليك سوى اتباع الخطوات أدناه.",
    seller_join_step1_title: "أنشئ حسابك",
    seller_join_step1_desc: "املأ استمارة التسجيل ببياناتك الشخصية وتفاصيل متجرك. لا يستغرق الأمر سوى بضع دقائق.",
    seller_join_step2_title: "قم بتحميل منتجاتك",
    seller_join_step2_desc: "بمجرد التسجيل ، يمكنك الوصول إلى لوحة تحكم البائع الخاصة بك لسرد منتجاتك الحلال المعتمدة وإعداد ملف تعريف متجрок.",
    seller_join_step3_title: "إرسال للمراجعة والبدء في البث المباشر",
    seller_join_step3_desc: "بعد إعداد متجرك ، أرسله للمراجعة النهائية. سيقوم فريقنا بالتحقق من شهاداتك ومنتجاتك قبل بدء البث المباشر.",
    seller_join_already_account: "هل لديك حساب بالفعل؟",
    seller_join_login_link: "تسجيل الدخول",
    seller_join_form_title: "تسجيل البائع",
    seller_join_form_desc: "أدخل التفاصيل الخاصة بك لإنشاء حساب بائع.",
    seller_form_first_name: "الاسم الأول",
    seller_form_last_name: "اسم العائلة",
    seller_form_store_name: "اسم المتجر",
    seller_form_email: "البريد الإلكتروني",
    seller_form_password: "كلمة المرور",
    seller_form_business_details: "عن عملك",
    seller_form_bank_account: "رقم الحساب المصرفي",
    seller_form_ifsc_code: "رمز IFSC",
    seller_form_gst: "رقم ضريبة السلع والخدمات",
    seller_form_document: "وثيقة التحقق",
    seller_form_document_upload: "انقر لتحميل المستند",
    seller_form_document_upload_desc: "(على سبيل المثال ، شهادة ضريبة السلع والخدمات ، رخصة تجارية)",
    seller_form_document_selected: "الملف المحدد:",
    seller_form_document_none: "لم يتم تحديد أي ملف.",
    seller_form_submit_button: "إنشاء حساب وتقديمه للمراجعة",
    seller_form_submitting_button: "جارٍ الإرسال للمراجعة ...",
    seller_form_first_name_placeholder: "جون",
    seller_form_last_name_placeholder: "دو",
    seller_form_store_name_placeholder: "متجري الرائع",
    seller_form_business_details_placeholder: "صف عملك والمنتجات التي تبيعها وحالة شهادة الحلال الخاصة بك ...",
    seller_form_bank_account_placeholder: "رقم حسابك المصرفي",
    seller_form_ifsc_code_placeholder: "رمز IFSC الخاص بالمصرف الذي تتعامل معه",
    seller_form_gst_placeholder: "رقم تعريف ضريبة السلع والخدمات (اختياري)"
  },
  tr: {
    hero_headline: "İnancın Lüksle Buluştuğu Yer",
    hero_subtext: "İçinizin rahat olması ve değerleriniz için özenle seçilmiş ve özgünlüğü doğrulanmış birinci sınıf helal ürünlerden oluşan güvenilir bir pazar yerini keşfedin.",
    hero_cta: "Koleksiyona Girin",
    nav_home: "Ana Sayfa",
    nav_products: "Ürünler",
    nav_about: "Hakkımızda",
    nav_contact: "İletişim",
    nav_admin_dashboard: "Yönetici Paneli",
    nav_become_seller: "Satıcı Ol",
    nav_toggle_menu: "Menüyü Değiştir",
    nav_change_language: "Dili değiştir",
    nav_search: "Ara",
    nav_cart: "Alışveriş Sepeti",
    nav_user_menu: "Kullanıcı Menüsü",
    nav_my_account: "Hesabım",
    nav_profile: "Profil",
    nav_seller_dashboard: "Satıcı Paneli",
    nav_store_settings: "Mağaza Ayarları",
    nav_logout: "Çıkış Yap",
    nav_login: "Giriş Yap",
    lang_en: "İngilizce",
    lang_hi: "Hintçe",
    lang_ur: "Urduca",
    lang_ar: "Arapça",
    lang_tr: "Türkçe",
    lang_ms: "Malayca",
    lang_fr: "Fransızca",
    footer_about: "Hakkımızda",
    footer_contact: "İletişim",
    footer_terms: "Hizmet Şartları",
    footer_privacy: "Gizlilik Politikası",
    footer_rights: "Tüm hakları saklıdır.",
    recommendations_title: "Sadece Sana Özel",
    featured_products_title: "Öne Çıkan Ürünler",
    view_all_cta: "Tümünü Görüntüle",
    product_halal_certified: "Helal Sertifikalı",
    product_add_to_cart: "Sepete Ekle",
    product_add_to_wishlist: "İstek Listesine Ekle",
    product_remove_from_wishlist: "İstek Listesinden Kaldır",
    breadcrumb_home: "Ana Sayfa",
    about_us_breadcrumb: "Hakkımızda",
    about_our_story_title: "Hikayemiz",
    about_our_story_desc: "Jalal Bazaar basit bir fikirden doğdu: tüketicilerin yüksek kaliteli, otantik helal ürünleri bulmaları için güvenilir, zarif ve kullanışlı bir çevrimiçi alan yaratmak.",
    about_image_alt: "Birlikte çalışan çeşitli bir ekip",
    about_commitment_title: "Özgünlük ve İnanca Bağlılık",
    about_commitment_desc: "Helal sertifikalı teklifleriyle gurur duyan seçici tüketiciler ve etik satıcılar arasındaki boşluğu dolduruyoruz.",
    about_mission_title: "Misyonumuz",
    about_mission_desc: "Misyonumuz Müslüman tüketicileri ve girişimcileri güçlendirmektir. Her satıcıyı ve ürünü katı helal standartlarını karşıladıklarından emin olmak için titizlikle inceliyor, her satın alımda gönül rahatlığı sağlıyoruz. Bir pazar yerinden daha fazlası olmayı hedefliyoruz; modern Müslüman yaşam tarzının temel taşı olmak, mirasımızı kutlarken geleceği kucaklamak istiyoruz.",
    about_vision_title: "Vizyonumuz",
    about_vision_desc: "Her Müslüman tüketicinin nerede olursa olsun değerleriyle uyumlu ürünlere kolayca erişebildiği bir dünya tasavvur ediyoruz. Küresel bir topluluk oluşturmaya, helal işletmeler için ekonomik büyümeyi teşvik etmeye ve güven, kalite ve paylaşılan inanç temelli ilkelerden oluşan canlı bir ekosistem yaratmaya çalışıyoruz.",
    cart_breadcrumb: "Alışveriş Sepeti",
    cart_title: "Sepetiniz",
    cart_description: "Ürünlerinizi gözden geçirin ve ödemeye devam edin.",
    cart_empty_title: "Sepetiniz boş",
    cart_empty_desc: "Görünüşe göre sepetinize henüz bir şey eklemediniz.",
    cart_start_shopping: "Alışverişe Başla",
    cart_summary_title: "Sipariş Özeti",
    cart_summary_subtotal: "Ara Toplam",
    cart_summary_shipping: "Kargo",
    cart_summary_shipping_free: "Ücretsiz",
    cart_summary_total: "Toplam",
    cart_proceed_to_checkout: "Ödemeye Devam Et",
    cart_remove_item: "Ürünü kaldır",
    breadcrumb_cart: "Sepet",
    breadcrumb_checkout: "Ödeme",
    checkout_title: "Ödeme",
    checkout_description: "Aşağıdaki bilgileri sağlayarak satın alma işleminizi tamamlayın.",
    checkout_form_title: "İletişim ve Kargo",
    checkout_form_email: "E-posta Adresi",
    checkout_form_first_name: "İsim",
    checkout_form_last_name: "Soyadı",
    checkout_form_address: "Adres",
    checkout_form_city: "Şehir",
    checkout_form_country: "Ülke",
    checkout_form_postal_code: "Posta Kodu",
    checkout_form_pay: "Öde",
    checkout_form_with_razorpay: "Razorpay ile",
    checkout_form_processing: "İşleniyor...",
    checkout_toast_empty_cart_title: "Sepetiniz boş",
    checkout_toast_empty_cart_desc: "Lütfen ödeme yapmadan önce sepetinize ürün ekleyin.",
    checkout_razorpay_desc: "Helal Pazar Yeri Alışverişiniz",
    checkout_toast_order_placed_title: "Siparişiniz alındı!",
    checkout_toast_order_placed_desc: "Satın aldığınız için teşekkür ederiz. Ödeme Kimliği:",
    breadcrumb_contact: "Bize Ulaşın",
    contact_title: "İletişime Geçin",
    contact_description: "Sizden haber almak isteriz. Ürünlerimiz, satıcılarımız veya başka bir şey hakkında bir sorunuz olursa olsun, ekibimiz tüm sorularınızı yanıtlamaya hazırdır.",
    contact_form_first_name: "İsim",
    contact_form_last_name: "Soyadı",
    contact_form_email: "E-posta",
    contact_form_message: "Mesaj",
    contact_form_send: "Mesaj Gönder",
    products_title: "Koleksiyonumuz",
    products_description: "Özenle seçilmiş otantik helal ürünlerimizi keşfedin.",
    products_search_placeholder: "Ürün ara...",
    products_filter_placeholder: "Kategoriye göre filtrele",
    products_all_categories: "Tüm Kategoriler",
    products_none_found_title: "Ürün Bulunamadı",
    products_none_found_desc: "Aramanızı veya filtrelerinizi değiştirmeyi deneyin.",
    wishlist_title: "İstek Listesi",
    wishlist_description: "Favori ürünleriniz, hepsi tek bir yerde.",
    wishlist_empty_title: "İstek listeniz boş",
    wishlist_empty_description: "Ürünleri keşfedin ve favorilerinizi buraya ekleyin.",
    wishlist_discover_products: "Ürünleri Keşfedin",
    toast_added_to_cart: "sepetinize eklendi.",
    toast_removed_from_cart: "Ürün sepetinizden kaldırıldı.",
    toast_added_to_wishlist: "istek listenize eklendi.",
    toast_removed_from_wishlist: "istek listenizden kaldırıldı.",
    seller_join_badge: "Yolculuğunuza Başlayın",
    seller_join_title: "Jalal Bazaar'da Satıcı Olun",
    seller_join_description: "Küresel bir kitleye otantik helal ürünler sunan güvenilir satıcılardan oluşan bir topluluğa katılın. İşinizi büyütmeniz için ihtiyacınız olan araçları sağlıyoruz.",
    seller_join_steps_title: "3 Kolay Adımda Satışa Başlayın",
    seller_join_steps_desc: "Başlamak çok kolay. Sadece aşağıdaki adımları izleyin.",
    seller_join_step1_title: "Hesabınızı Oluşturun",
    seller_join_step1_desc: "Kayıt formunu kişisel ve mağaza bilgilerinizle doldurun. Sadece birkaç dakika sürer.",
    seller_join_step2_title: "Ürünlerinizi Yükleyin",
    seller_join_step2_desc: "Kaydolduktan sonra, helal sertifikalı ürünlerinizi listelemek ve mağaza profilinizi oluşturmak için satıcı panelinize erişebilirsiniz.",
    seller_join_step3_title: "İncelemeye Gönderin ve Yayına Başlayın",
    seller_join_step3_desc: "Mağazanızı kurduktan sonra son bir inceleme için gönderin. Ekibimiz, yayına başlamadan önce sertifikalarınızı ve ürünlerinizi doğrulayacaktır.",
    seller_join_already_account: "Zaten bir hesabınız var mı?",
    seller_join_login_link: "Giriş Yap",
    seller_join_form_title: "Satıcı Kaydı",
    seller_join_form_desc: "Satıcı hesabınızı oluşturmak için bilgilerinizi girin.",
    seller_form_first_name: "İsim",
    seller_form_last_name: "Soyadı",
    seller_form_store_name: "Mağaza Adı",
    seller_form_email: "E-posta",
    seller_form_password: "Şifre",
    seller_form_business_details: "İşletmeniz Hakkında",
    seller_form_bank_account: "Banka Hesap Numarası",
    seller_form_ifsc_code: "IFSC Kodu",
    seller_form_gst: "GST Numarası",
    seller_form_document: "Doğrulama Belgesi",
    seller_form_document_upload: "Belge yüklemek için tıklayın",
    seller_form_document_upload_desc: "(örn. GST Sertifikası, İşletme Lisansı)",
    seller_form_document_selected: "Seçilen dosya:",
    seller_form_document_none: "Dosya seçilmedi.",
    seller_form_submit_button: "Hesap Oluştur ve İncelemeye Gönder",
    seller_form_submitting_button: "İncelemeye gönderiliyor...",
    seller_form_first_name_placeholder: "Ahmet",
    seller_form_last_name_placeholder: "Yılmaz",
    seller_form_store_name_placeholder: "Harika Mağazam",
    seller_form_business_details_placeholder: "İşletmenizi, sattığınız ürünleri ve helal sertifika durumunuzu açıklayın...",
    seller_form_bank_account_placeholder: "Banka hesap numaranız",
    seller_form_ifsc_code_placeholder: "Bankanızın IFSC kodu",
    seller_form_gst_placeholder: "GSTIN (isteğe bağlı)"
  },
  ms: {
    hero_headline: "Di Mana Iman Bertemu Kemewahan",
    hero_subtext: "Terokai pasaran produk halal premium yang dipercayai — disusun dengan teliti dan disahkan secara sahih untuk ketenangan fikiran dan nilai anda.",
    hero_cta: "Masuk Koleksi",
    nav_home: "Utama",
    nav_products: "Produk",
    nav_about: "Tentang Kami",
    nav_contact: "Hubungi",
    nav_admin_dashboard: "Papan Pemuka Pentadbir",
    nav_become_seller: "Jadi Penjual",
    nav_toggle_menu: "Togol Menu",
    nav_change_language: "Tukar bahasa",
    nav_search: "Cari",
    nav_cart: "Troli Beli-belah",
    nav_user_menu: "Menu Pengguna",
    nav_my_account: "Akaun Saya",
    nav_profile: "Profil",
    nav_seller_dashboard: "Papan Pemuka Penjual",
    nav_store_settings: "Tetapan Kedai",
    nav_logout: "Log Keluar",
    nav_login: "Log Masuk",
    lang_en: "Inggeris",
    lang_hi: "Hindi",
    lang_ur: "Urdu",
    lang_ar: "Arab",
    lang_tr: "Turki",
    lang_ms: "Melayu",
    lang_fr: "Perancis",
    footer_about: "Tentang Kami",
    footer_contact: "Hubungi",
    footer_terms: "Syarat Perkhidmatan",
    footer_privacy: "Dasar Privasi",
    footer_rights: "Hak cipta terpelihara.",
    recommendations_title: "Hanya Untuk Anda",
    featured_products_title: "Produk Pilihan",
    view_all_cta: "Lihat Semua",
    product_halal_certified: "Disahkan Halal",
    product_add_to_cart: "Tambah ke Troli",
    product_add_to_wishlist: "Tambah ke Senarai Hajat",
    product_remove_from_wishlist: "Keluarkan dari Senarai Hajat",
    breadcrumb_home: "Utama",
    about_us_breadcrumb: "Tentang Kami",
    about_our_story_title: "Kisah Kami",
    about_our_story_desc: "Jalal Bazaar lahir dari idea mudah: untuk mewujudkan ruang dalam talian yang dipercayai, elegan dan mudah bagi pengguna untuk mencari produk halal yang berkualiti tinggi dan sahih.",
    about_image_alt: "Pasukan yang pelbagai bekerja bersama",
    about_commitment_title: "Berkomitmen pada Keaslian dan Kepercayaan",
    about_commitment_desc: "Kami merapatkan jurang antara pengguna yang arif dan penjual beretika yang berbangga dengan penawaran sijil halal mereka.",
    about_mission_title: "Misi Kami",
    about_mission_desc: "Misi kami adalah untuk memperkasakan pengguna dan usahawan Islam. Kami meneliti setiap penjual dan produk dengan teliti untuk memastikan mereka memenuhi standard halal yang ketat, memberikan ketenangan fikiran dengan setiap pembelian. Kami berhasrat untuk menjadi lebih daripada sekadar pasaran; kami ingin menjadi landasan gaya hidup Muslim moden, meraikan warisan kami sambil menerima masa depan.",
    about_vision_title: "Visi Kami",
    about_vision_desc: "Kami membayangkan dunia di mana setiap pengguna Islam mempunyai akses mudah kepada produk yang selaras dengan nilai mereka, tidak kira di mana mereka berada. Kami berusaha untuk membina komuniti global, memupuk pertumbuhan ekonomi untuk perniagaan halal dan mewujudkan ekosistem yang cergas berasaskan kepercayaan, kualiti dan prinsip berasaskan kepercayaan bersama.",
    cart_breadcrumb: "Troli Beli-belah",
    cart_title: "Troli Anda",
    cart_description: "Semak barang anda dan teruskan ke pembayaran.",
    cart_empty_title: "Troli anda kosong",
    cart_empty_desc: "Nampaknya anda belum menambah apa-apa ke troli anda lagi.",
    cart_start_shopping: "Mula Membeli-belah",
    cart_summary_title: "Ringkasan Pesanan",
    cart_summary_subtotal: "Subjumlah",
    cart_summary_shipping: "Penghantaran",
    cart_summary_shipping_free: "Percuma",
    cart_summary_total: "Jumlah",
    cart_proceed_to_checkout: "Teruskan ke Pembayaran",
    cart_remove_item: "Keluarkan item",
    breadcrumb_cart: "Troli",
    breadcrumb_checkout: "Pembayaran",
    checkout_title: "Pembayaran",
    checkout_description: "Lengkapkan pembelian anda dengan memberikan butiran di bawah.",
    checkout_form_title: "Hubungan & Penghantaran",
    checkout_form_email: "Alamat E-mel",
    checkout_form_first_name: "Nama Pertama",
    checkout_form_last_name: "Nama Keluarga",
    checkout_form_address: "Alamat",
    checkout_form_city: "Bandar",
    checkout_form_country: "Negara",
    checkout_form_postal_code: "Poskod",
    checkout_form_pay: "Bayar",
    checkout_form_with_razorpay: "dengan Razorpay",
    checkout_form_processing: "Memproses...",
    checkout_toast_empty_cart_title: "Troli anda kosong",
    checkout_toast_empty_cart_desc: "Sila tambah item ke troli anda sebelum membuat pembayaran.",
    checkout_razorpay_desc: "Pembelian Pasaran Halal Anda",
    checkout_toast_order_placed_title: "Pesanan Dibuat!",
    checkout_toast_order_placed_desc: "Terima kasih atas pembelian anda. ID Pembayaran:",
    breadcrumb_contact: "Hubungi Kami",
    contact_title: "Hubungi Kami",
    contact_description: "Kami ingin mendengar daripada anda. Sama ada anda mempunyai soalan tentang produk kami, penjual, atau apa-apa sahaja, pasukan kami bersedia untuk menjawab semua soalan anda.",
    contact_form_first_name: "Nama pertama",
    contact_form_last_name: "Nama keluarga",
    contact_form_email: "E-mel",
    contact_form_message: "Mesej",
    contact_form_send: "Hantar Mesej",
    products_title: "Koleksi Kami",
    products_description: "Terokai pilihan produk halal asli kami yang dipilih susun.",
    products_search_placeholder: "Cari produk...",
    products_filter_placeholder: "Tapis mengikut kategori",
    products_all_categories: "Semua Kategori",
    products_none_found_title: "Tiada Produk Ditemui",
    products_none_found_desc: "Cuba laraskan carian atau penapis anda.",
    wishlist_title: "Senarai Hajat",
    wishlist_description: "Barangan kegemaran anda, semuanya di satu tempat.",
    wishlist_empty_title: "Senarai hajat anda kosong",
    wishlist_empty_description: "Terokai produk dan tambah kegemaran anda di sini.",
    wishlist_discover_products: "Terokai Produk",
    toast_added_to_cart: "telah ditambahkan ke troli anda.",
    toast_removed_from_cart: "Item telah dialih keluar daripada troli anda.",
    toast_added_to_wishlist: "telah ditambahkan pada senarai hajat anda.",
    toast_removed_from_wishlist: "telah dialih keluar daripada senarai hajat anda.",
    seller_join_badge: "Mulakan Perjalanan Anda",
    seller_join_title: "Jadi Penjual di Jalal Bazaar",
    seller_join_description: "Sertai komuniti vendor yang dipercayai yang menyediakan produk halal asli kepada khalayak global. Kami menyediakan alatan yang anda perlukan untuk mengembangkan perniagaan anda.",
    seller_join_steps_title: "Mula Menjual dalam 3 Langkah Mudah",
    seller_join_steps_desc: "Sangat mudah untuk bermula. Ikuti sahaja langkah-langkah di bawah.",
    seller_join_step1_title: "Buat Akaun Anda",
    seller_join_step1_desc: "Isi borang pendaftaran dengan butiran peribadi dan kedai anda. Ia hanya mengambil masa beberapa minit.",
    seller_join_step2_title: "Muat Naik Produk Anda",
    seller_join_step2_desc: "Setelah mendaftar, anda boleh mengakses papan pemuka penjual anda untuk menyenaraikan produk yang disahkan halal dan menyediakan profil kedai anda.",
    seller_join_step3_title: "Hantar untuk Semakan & Siaran Langsung",
    seller_join_step3_desc: "Selepas anda menyediakan kedai anda, hantarkannya untuk semakan akhir. Pasukan kami akan mengesahkan pensijilan dan produk anda sebelum anda disiarkan secara langsung.",
    seller_join_already_account: "Sudah mempunyai akaun?",
    seller_join_login_link: "Log Masuk",
    seller_join_form_title: "Pendaftaran Penjual",
    seller_join_form_desc: "Masukkan butiran anda untuk membuat akaun penjual anda.",
    seller_form_first_name: "Nama Pertama",
    seller_form_last_name: "Nama Keluarga",
    seller_form_store_name: "Nama Kedai",
    seller_form_email: "E-mel",
    seller_form_password: "Kata Laluan",
    seller_form_business_details: "Mengenai Perniagaan Anda",
    seller_form_bank_account: "Nombor Akaun Bank",
    seller_form_ifsc_code: "Kod IFSC",
    seller_form_gst: "Nombor GST",
    seller_form_document: "Dokumen Pengesahan",
    seller_form_document_upload: "Klik untuk memuat naik dokumen",
    seller_form_document_upload_desc: "(cth., Sijil GST, Lesen Perniagaan)",
    seller_form_document_selected: "Fail yang dipilih:",
    seller_form_document_none: "Tiada fail dipilih.",
    seller_form_submit_button: "Buat Akaun & Hantar untuk Semakan",
    seller_form_submitting_button: "Menghantar untuk semakan...",
    seller_form_first_name_placeholder: "Ahmad",
    seller_form_last_name_placeholder: "bin Abdullah",
    seller_form_store_name_placeholder: "Kedai Hebat Saya",
    seller_form_business_details_placeholder: "Terangkan perniagaan anda, produk yang anda jual, dan status pensijilan halal anda...",
    seller_form_bank_account_placeholder: "Nombor akaun bank anda",
    seller_form_ifsc_code_placeholder: "Kod IFSC bank anda",
    seller_form_gst_placeholder: "GSTIN (pilihan)"
  },
  fr: {
    hero_headline: "Où la Foi Rencontre le Luxe",
    hero_subtext: "Explorez un marché de confiance de produits halal haut de gamme — soigneusement sélectionnés et authentiquement vérifiés pour votre tranquillité d'esprit et vos valeurs.",
    hero_cta: "Entrez dans la Collection",
    nav_home: "Accueil",
    nav_products: "Produits",
    nav_about: "À Propos",
    nav_contact: "Contact",
    nav_admin_dashboard: "Tableau de Bord Admin",
    nav_become_seller: "Devenir Vendeur",
    nav_toggle_menu: "Basculer le menu",
    nav_change_language: "Changer de langue",
    nav_search: "Rechercher",
    nav_cart: "Panier d'Achat",
    nav_user_menu: "Menu Utilisateur",
    nav_my_account: "Mon Compte",
    nav_profile: "Profil",
    nav_seller_dashboard: "Tableau de Bord Vendeur",
    nav_store_settings: "Paramètres de la Boutique",
    nav_logout: "Se Déconnecter",
    nav_login: "Se Connecter",
    lang_en: "Anglais",
    lang_hi: "Hindi",
    lang_ur: "Ourdou",
    lang_ar: "Arabe",
    lang_tr: "Turc",
    lang_ms: "Malais",
    lang_fr: "Français",
    footer_about: "À Propos",
    footer_contact: "Contact",
    footer_terms: "Conditions d'Utilisation",
    footer_privacy: "Politique de Confidentialité",
    footer_rights: "Tous droits réservés.",
    recommendations_title: "Juste Pour Vous",
    featured_products_title: "Produits Vedettes",
    view_all_cta: "Voir Tout",
    product_halal_certified: "Certifié Halal",
    product_add_to_cart: "Ajouter au Panier",
    product_add_to_wishlist: "Ajouter à la Liste de Souhaits",
    product_remove_from_wishlist: "Retirer de la Liste de Souhaits",
    breadcrumb_home: "Accueil",
    about_us_breadcrumb: "À Propos",
    about_our_story_title: "Notre Histoire",
    about_our_story_desc: "Jalal Bazaar est né d'une idée simple : créer un espace en ligne de confiance, élégant et pratique pour que les consommateurs trouvent des produits halal de haute qualité et authentiques.",
    about_image_alt: "Équipe diversifiée travaillant ensemble",
    about_commitment_title: "Engagé envers l'Authenticité et la Foi",
    about_commitment_desc: "Nous comblons le fossé entre les consommateurs avertis et les vendeurs éthiques qui sont fiers de leurs offres certifiées halal.",
    about_mission_title: "Notre Mission",
    about_mission_desc: "Notre mission est de responsabiliser les consommateurs et les entrepreneurs musulmans. Nous examinons méticuleusement chaque vendeur et produit pour nous assurer qu'ils respectent des normes halal strictes, offrant une tranquillité d'esprit à chaque achat. Nous aspirons à être plus qu'un simple marché ; nous voulons être une pierre angulaire du style de vie musulman moderne, célébrant notre héritage tout en embrassant l'avenir.",
    about_vision_title: "Notre Vision",
    about_vision_desc: "Nous envisageons un monde où chaque consommateur musulman a un accès facile à des produits qui correspondent à ses valeurs, où qu'il se trouve. Nous nous efforçons de construire une communauté mondiale, en favorisant la croissance économique des entreprises halal et en créant un écosystème dynamique de confiance, de qualité et de principes partagés basés sur la foi.",
    cart_breadcrumb: "Panier d'Achat",
    cart_title: "Votre Panier",
    cart_description: "Vérifiez vos articles et procédez au paiement.",
    cart_empty_title: "Votre panier est vide",
    cart_empty_desc: "Il semble que vous n'ayez encore rien ajouté à votre panier.",
    cart_start_shopping: "Commencer les Achats",
    cart_summary_title: "Résumé de la Commande",
    cart_summary_subtotal: "Sous-total",
    cart_summary_shipping: "Livraison",
    cart_summary_shipping_free: "Gratuite",
    cart_summary_total: "Total",
    cart_proceed_to_checkout: "Passer à la Caisse",
    cart_remove_item: "Retirer l'article",
    breadcrumb_cart: "Panier",
    breadcrumb_checkout: "Paiement",
    checkout_title: "Paiement",
    checkout_description: "Finalisez votre achat en fournissant les détails ci-dessous.",
    checkout_form_title: "Contact et Livraison",
    checkout_form_email: "Adresse E-mail",
    checkout_form_first_name: "Prénom",
    checkout_form_last_name: "Nom de Famille",
    checkout_form_address: "Adresse",
    checkout_form_city: "Ville",
    checkout_form_country: "Pays",
    checkout_form_postal_code: "Code Postal",
    checkout_form_pay: "Payer",
    checkout_form_with_razorpay: "avec Razorpay",
    checkout_form_processing: "En cours de traitement...",
    checkout_toast_empty_cart_title: "Votre panier est vide",
    checkout_toast_empty_cart_desc: "Veuillez ajouter des articles à votre panier avant de passer à la caisse.",
    checkout_razorpay_desc: "Votre Achat sur le Marché Halal",
    checkout_toast_order_placed_title: "Commande Passée !",
    checkout_toast_order_placed_desc: "Merci pour votre achat. ID de paiement :",
    breadcrumb_contact: "Nous Contacter",
    contact_title: "Prenez Contact",
    contact_description: "Nous serions ravis d'avoir de vos nouvelles. Que vous ayez une question sur nos produits, nos vendeurs ou toute autre chose, notre équipe est prête à répondre à toutes vos questions.",
    contact_form_first_name: "Prénom",
    contact_form_last_name: "Nom de famille",
    contact_form_email: "E-mail",
    contact_form_message: "Message",
    contact_form_send: "Envoyer le Message",
    products_title: "Notre Collection",
    products_description: "Explorez notre sélection de produits halal authentiques.",
    products_search_placeholder: "Rechercher des produits...",
    products_filter_placeholder: "Filtrer par catégorie",
    products_all_categories: "Toutes les Catégories",
    products_none_found_title: "Aucun Produit Trouvé",
    products_none_found_desc: "Essayez d'ajuster votre recherche ou vos filtres.",
    wishlist_title: "Liste de Souhaits",
    wishlist_description: "Vos articles préférés, tous au même endroit.",
    wishlist_empty_title: "Votre liste de souhaits est vide",
    wishlist_empty_description: "Explorez les produits et ajoutez vos favoris ici.",
    wishlist_discover_products: "Découvrir les Produits",
    toast_added_to_cart: "a été ajouté à votre panier.",
    toast_removed_from_cart: "L'article a été retiré de votre panier.",
    toast_added_to_wishlist: "a été ajouté à votre liste de souhaits.",
    toast_removed_from_wishlist: "a été retiré de votre liste de souhaits.",
    seller_join_badge: "Commencez Votre Voyage",
    seller_join_title: "Devenez Vendeur sur Jalal Bazaar",
    seller_join_description: "Rejoignez une communauté de vendeurs de confiance fournissant des produits halal authentiques à un public mondial. Nous fournissons les outils dont vous avez besoin pour développer votre entreprise.",
    seller_join_steps_title: "Commencez à Vendre en 3 Étapes Faciles",
    seller_join_steps_desc: "C'est facile de commencer. Suivez simplement les étapes ci-dessous.",
    seller_join_step1_title: "Créez Votre Compte",
    seller_join_step1_desc: "Remplissez le formulaire d'inscription avec vos informations personnelles et celles de votre boutique. Cela ne prend que quelques minutes.",
    seller_join_step2_title: "Téléchargez Vos Produits",
    seller_join_step2_desc: "Une fois inscrit, vous pouvez accéder à votre tableau de bord de vendeur pour lister vos produits certifiés halal et configurer le profil de votre boutique.",
    seller_join_step3_title: "Soumettre pour Examen et Mettre en Ligne",
    seller_join_step3_desc: "Après avoir configuré votre boutique, soumettez-la pour un examen final. Notre équipe vérifiera vos certifications et vos produits avant votre mise en ligne.",
    seller_join_already_account: "Vous avez déjà un compte ?",
    seller_join_login_link: "Se Connecter",
    seller_join_form_title: "Inscription du Vendeur",
    seller_join_form_desc: "Entrez vos coordonnées pour créer votre compte vendeur.",
    seller_form_first_name: "Prénom",
    seller_form_last_name: "Nom de famille",
    seller_form_store_name: "Nom de la Boutique",
    seller_form_email: "E-mail",
    seller_form_password: "Mot de passe",
    seller_form_business_details: "À propos de Votre Entreprise",
    seller_form_bank_account: "Numéro de Compte Bancaire",
    seller_form_ifsc_code: "Code IFSC",
    seller_form_gst: "Numéro GST",
    seller_form_document: "Document de Vérification",
    seller_form_document_upload: "Cliquez pour télécharger le document",
    seller_form_document_upload_desc: "(par exemple, Certificat GST, Licence Commerciale)",
    seller_form_document_selected: "Fichier sélectionné :",
    seller_form_document_none: "Aucun fichier sélectionné.",
    seller_form_submit_button: "Créer un Compte et Soumettre pour Examen",
    seller_form_submitting_button: "Soumission pour examen en cours...",
    seller_form_first_name_placeholder: "Jean",
    seller_form_last_name_placeholder: "Dupont",
    seller_form_store_name_placeholder: "Ma Super Boutique",
    seller_form_business_details_placeholder: "Décrivez votre entreprise, les produits que vous vendez et votre statut de certification halal...",
    seller_form_bank_account_placeholder: "Votre numéro de compte bancaire",
    seller_form_ifsc_code_placeholder: "Le code IFSC de votre banque",
    seller_form_gst_placeholder: "GSTIN (facultatif)"
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
    const storedLang = localStorage.getItem("jalal-language") as Language | null;
    if (storedLang && translations[storedLang]) {
      setLanguageState(storedLang);
    }
  }, []);

  useEffect(() => {
      if (isMounted) {
        document.documentElement.lang = language;
        document.documentElement.dir = (language === 'ar' || language === 'ur') ? 'rtl' : 'ltr';
      }
  }, [language, isMounted]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if(isMounted) {
        localStorage.setItem("jalal-language", lang);
    }
  };

  const t = useCallback((key: string): string => {
    return translations[language]?.[key] || translations['en'][key] || key;
  }, [language]);


  const value = {
    language,
    setLanguage,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
