
"use client";

import { createContext, useContext, useState, ReactNode, useEffect, useCallback } from "react";

type Language = "en" | "hi" | "ur" | "ar";

const translations: Record<Language, Record<string, string>> = {
  en: {
    hero_headline: "Where Faith Meets Luxury",
    hero_subtext: "Explore a trusted marketplace of premium halal products — carefully curated and authentically verified for your peace of mind and values.",
    hero_cta: "Enter the Collection",
    nav_home: "Home",
    nav_products: "Products",
    nav_about: "About Us",
    nav_contact: "Contact",
    nav_admin_dashboard: "Admin Dashboard",
    nav_become_seller: "Become a Seller",
    nav_toggle_menu: "Toggle Menu",
    nav_change_language: "Change language",
    nav_search: "Search",
    nav_cart: "Shopping Cart",
    nav_user_menu: "User Menu",
    nav_my_account: "My Account",
    nav_profile: "Profile",
    nav_seller_dashboard: "Seller Dashboard",
    nav_store_settings: "Store Settings",
    nav_logout: "Log out",
    nav_login: "Login",
    lang_en: "English",
    lang_hi: "Hindi",
    lang_ur: "Urdu",
    lang_ar: "Arabic",
    footer_about: "About Us",
    footer_contact: "Contact",
    footer_terms: "Terms of Service",
    footer_privacy: "Privacy Policy",
    footer_rights: "All rights reserved.",
    recommendations_title: "Just For You",
    featured_products_title: "Featured Products",
    view_all_cta: "View All",
    product_halal_certified: "Halal Certified",
    product_add_to_cart: "Add to Cart",
    product_add_to_wishlist: "Add to Wishlist",
    product_remove_from_wishlist: "Remove from Wishlist",
    breadcrumb_home: "Home",
    about_us_breadcrumb: "About Us",
    about_our_story_title: "Our Story",
    about_our_story_desc: "Jalal Bazaar was born from a simple idea: to create a trusted, elegant, and convenient online space for consumers to find high-quality, authentic halal products.",
    about_image_alt: "Diverse team working together",
    about_commitment_title: "Committed to Authenticity and Faith",
    about_commitment_desc: "We bridge the gap between discerning consumers and ethical sellers who are proud of their halal-certified offerings.",
    about_mission_title: "Our Mission",
    about_mission_desc: "Our mission is to empower Muslim consumers and entrepreneurs. We meticulously vet every seller and product to ensure they meet strict halal standards, providing peace of mind with every purchase. We aim to be more than a marketplace; we want to be a cornerstone of the modern Muslim lifestyle, celebrating our heritage while embracing the future.",
    about_vision_title: "Our Vision",
    about_vision_desc: "We envision a world where every Muslim consumer has easy access to products that align with their values, no matter where they are. We strive to build a global community, fostering economic growth for halal businesses and creating a vibrant ecosystem of trust, quality, and shared faith-based principles.",
    cart_breadcrumb: "Shopping Cart",
    cart_title: "Your Cart",
    cart_description: "Review your items and proceed to checkout.",
    cart_empty_title: "Your cart is empty",
    cart_empty_desc: "Looks like you haven't added anything to your cart yet.",
    cart_start_shopping: "Start Shopping",
    cart_summary_title: "Order Summary",
    cart_summary_subtotal: "Subtotal",
    cart_summary_shipping: "Shipping",
    cart_summary_shipping_free: "Free",
    cart_summary_total: "Total",
    cart_proceed_to_checkout: "Proceed to Checkout",
    cart_remove_item: "Remove item",
    breadcrumb_cart: "Cart",
    breadcrumb_checkout: "Checkout",
    checkout_title: "Checkout",
    checkout_description: "Complete your purchase by providing the details below.",
    checkout_form_title: "Contact & Shipping",
    checkout_form_email: "Email Address",
    checkout_form_first_name: "First Name",
    checkout_form_last_name: "Last Name",
    checkout_form_address: "Address",
    checkout_form_city: "City",
    checkout_form_country: "Country",
    checkout_form_postal_code: "Postal Code",
    checkout_form_pay: "Pay",
    checkout_form_with_razorpay: "with Razorpay",
    checkout_form_processing: "Processing...",
    checkout_toast_empty_cart_title: "Your cart is empty",
    checkout_toast_empty_cart_desc: "Please add items to your cart before checking out.",
    checkout_razorpay_desc: "Your Halal Marketplace Purchase",
    checkout_toast_order_placed_title: "Order Placed!",
    checkout_toast_order_placed_desc: "Thank you for your purchase. Payment ID:",
    breadcrumb_contact: "Contact Us",
    contact_title: "Get In Touch",
    contact_description: "We'd love to hear from you. Whether you have a question about our products, sellers, or anything else, our team is ready to answer all your questions.",
    contact_form_first_name: "First name",
    contact_form_last_name: "Last name",
    contact_form_email: "Email",
    contact_form_message: "Message",
    contact_form_send: "Send Message",
    products_title: "Our Collection",
    products_description: "Explore our curated selection of authentic halal products.",
    products_search_placeholder: "Search products...",
    products_filter_placeholder: "Filter by category",
    products_all_categories: "All Categories",
    products_none_found_title: "No Products Found",
    products_none_found_desc: "Try adjusting your search or filters.",
    wishlist_title: "Wishlist",
    wishlist_description: "Your favorite items, all in one place.",
    wishlist_empty_title: "Your wishlist is empty",
    wishlist_empty_description: "Explore products and add your favorites here.",
    wishlist_discover_products: "Discover Products",
  },
  hi: {
    hero_headline: "आस्था विलासिता से मिलती है",
    hero_subtext: "प्रीमियम हलाल उत्पादों का एक विश्वसनीय बाज़ार खोजें - आपकी मन की शांति और मूल्यों के लिए सावधानीपूर्वक क्यूरेट और प्रमाणित रूप से सत्यापित।",
    hero_cta: "संग्रह में प्रवेश करें",
    nav_home: "होम",
    nav_products: "उत्पाद",
    nav_about: "हमारे बारे में",
    nav_contact: "संपर्क",
    nav_admin_dashboard: "एडमिन डैशबोर्ड",
    nav_become_seller: "विक्रेता बनें",
    nav_toggle_menu: "मेनू टॉगल करें",
    nav_change_language: "भाषा बदलें",
    nav_search: "खोज",
    nav_cart: "शॉपिंग कार्ट",
    nav_user_menu: "उपयोगकर्ता मेनू",
    nav_my_account: "मेरा खाता",
    nav_profile: "प्रोफ़ाइल",
    nav_seller_dashboard: "विक्रेता डैशबोर्ड",
    nav_store_settings: "स्टोर सेटिंग्स",
    nav_logout: "लॉग आउट",
    nav_login: "लॉग इन करें",
    lang_en: "अंग्रेजी",
    lang_hi: "हिंदी",
    lang_ur: "उर्दू",
    lang_ar: "अरबी",
    footer_about: "हमारे बारे में",
    footer_contact: "संपर्क",
    footer_terms: "सेवा की शर्तें",
    footer_privacy: "गोपनीयता नीति",
    footer_rights: "सर्वाधिकार सुरक्षित।",
    recommendations_title: "केवल आपके लिए",
    featured_products_title: "विशेष रुप से प्रदर्शित उत्पाद",
    view_all_cta: "सभी देखें",
    product_halal_certified: "हलाल प्रमाणित",
    product_add_to_cart: "कार्ट में डालें",
    product_add_to_wishlist: "इच्छा-सूची में जोड़ें",
    product_remove_from_wishlist: "इच्छा-सूची से हटाएं",
    breadcrumb_home: "होम",
    about_us_breadcrumb: "हमारे बारे में",
    about_our_story_title: "हमारी कहानी",
    about_our_story_desc: "जलाल बाज़ार का जन्म एक साधारण विचार से हुआ: उपभोक्ताओं को उच्च-गुणवत्ता, प्रामाणिक हलाल उत्पाद खोजने के लिए एक विश्वसनीय, सुंदर और सुविधाजनक ऑनलाइन स्थान बनाना।",
    about_image_alt: "विविध टीम एक साथ काम कर रही है",
    about_commitment_title: "प्रामाणिकता और आस्था के प्रति प्रतिबद्ध",
    about_commitment_desc: "हम समझदार उपभोक्ताओं और नैतिक विक्रेताओं के बीच की खाई को पाटते हैं जो अपनी हलाल-प्रमाणित पेशकशों पर गर्व करते हैं।",
    about_mission_title: "हमारा विशेष कार्य",
    about_mission_desc: "हमारा मिशन मुस्लिम उपभोक्ताओं और उद्यमियों को सशक्त बनाना है। हम यह सुनिश्चित करने के लिए हर विक्रेता और उत्पाद की सावधानीपूर्वक जांच करते हैं कि वे सख्त हलाल मानकों को पूरा करते हैं, जिससे हर खरीद के साथ मानसिक शांति मिलती है। हमारा लक्ष्य एक बाज़ार से कहीं ज़्यादा होना है; हम आधुनिक मुस्लिम जीवन शैली का एक आधार बनना चाहते हैं, अपनी विरासत का जश्न मनाते हुए भविष्य को अपनाते हैं।",
    about_vision_title: "हमारा नज़रिया",
    about_vision_desc: "हम एक ऐसी दुनिया की कल्पना करते हैं जहां हर मुस्लिम उपभोक्ता को उन उत्पादों तक आसान पहुंच हो जो उनके मूल्यों के अनुरूप हों, चाहे वे कहीं भी हों। हम एक वैश्विक समुदाय बनाने, हलाल व्यवसायों के लिए आर्थिक विकास को बढ़ावा देने और विश्वास, गुणवत्ता और साझा आस्था-आधारित सिद्धांतों का एक जीवंत पारिस्थितिकी तंत्र बनाने का प्रयास करते हैं।",
    cart_breadcrumb: "शॉपिंग कार्ट",
    cart_title: "आपकी गाड़ी",
    cart_description: "अपने आइटम की समीक्षा करें और चेकआउट के लिए आगे बढ़ें।",
    cart_empty_title: "आपकी गाड़ी खाली है",
    cart_empty_desc: "लगता है आपने अभी तक अपनी कार्ट में कुछ भी नहीं जोड़ा है।",
    cart_start_shopping: "खरीदारी शुरू करें",
    cart_summary_title: "आदेश सारांश",
    cart_summary_subtotal: "उप-योग",
    cart_summary_shipping: "शिपिंग",
    cart_summary_shipping_free: "नि: शुल्क",
    cart_summary_total: "कुल",
    cart_proceed_to_checkout: "चेकआउट करने के लिए आगे बढ़ें",
    cart_remove_item: "आइटम निकालें",
    breadcrumb_cart: "कार्ट",
    breadcrumb_checkout: "चेक आउट",
    checkout_title: "चेक आउट",
    checkout_description: "नीचे दिए गए विवरण प्रदान करके अपनी खरीद पूरी करें।",
    checkout_form_title: "संपर्क और शिपिंग",
    checkout_form_email: "ईमेल पता",
    checkout_form_first_name: "पहला नाम",
    checkout_form_last_name: "अंतिम नाम",
    checkout_form_address: "पता",
    checkout_form_city: "शहर",
    checkout_form_country: "देश",
    checkout_form_postal_code: "डाक कोड",
    checkout_form_pay: "भुगतान करें",
    checkout_form_with_razorpay: "रेजरपे के साथ",
    checkout_form_processing: "प्रसंस्करण हो रहा है...",
    checkout_toast_empty_cart_title: "आपकी गाड़ी खाली है",
    checkout_toast_empty_cart_desc: "कृपया चेक आउट करने से पहले अपनी कार्ट में आइटम जोड़ें।",
    checkout_razorpay_desc: "आपकी हलाल मार्केटप्लेस खरीद",
    checkout_toast_order_placed_title: "आदेश दिया गया!",
    checkout_toast_order_placed_desc: "आपकी खरीद के लिए धन्यवाद। भुगतान आईडी:",
    breadcrumb_contact: "संपर्क करें",
    contact_title: "संपर्क में रहो",
    contact_description: "हमें आपसे सुनकर खुशी होगी। चाहे आपके पास हमारे उत्पादों, विक्रेताओं, या किसी और चीज़ के बारे में कोई प्रश्न हो, हमारी टीम आपके सभी सवालों का जवाब देने के लिए तैयार है।",
    contact_form_first_name: "पहला नाम",
    contact_form_last_name: "अंतिम नाम",
    contact_form_email: "ईमेल",
    contact_form_message: "संदेश",
    contact_form_send: "संदेश भेजो",
    products_title: "हमारा संग्रह",
    products_description: "प्रामाणिक हलाल उत्पादों के हमारे क्यूरेटेड चयन का अन्वेषण करें।",
    products_search_placeholder: "उत्पाद खोजें...",
    products_filter_placeholder: "श्रेणी के अनुसार फ़िल्टर करें",
    products_all_categories: "सभी श्रेणियाँ",
    products_none_found_title: "कोई उत्पाद नहीं मिला",
    products_none_found_desc: "अपनी खोज या फ़िल्टर समायोजित करने का प्रयास करें।",
    wishlist_title: "इच्छा-सूची",
    wishlist_description: "आपकी पसंदीदा वस्तुएँ, सब एक ही स्थान पर।",
    wishlist_empty_title: "आपकी इच्छा सूची खाली है",
    wishlist_empty_description: "उत्पादों का अन्वेषण करें और अपने पसंदीदा यहाँ जोड़ें।",
    wishlist_discover_products: "उत्पादों की खोज करें",
  },
  ur: {
    hero_headline: "جہاں ایمان عیش و عشرت سے ملتا ہے۔",
    hero_subtext: "پریمیم حلال مصنوعات کا ایک قابل اعتماد بازار دریافت کریں — آپ کے ذہنی سکون اور اقدار کے لیے احتیاط سے تیار اور مستند طور پر تصدیق شدہ۔",
    hero_cta: "مجموعہ میں داخل ہوں۔",
    nav_home: "گھر",
    nav_products: "مصنوعات",
    nav_about: "ہمارے بارے میں",
    nav_contact: "رابطہ کریں۔",
    nav_admin_dashboard: "ایڈمن ڈیش بورڈ",
    nav_become_seller: "بیچنے والے بنیں۔",
    nav_toggle_menu: "مینو کو ٹوگل کریں۔",
    nav_change_language: "زبان تبدیل کریں",
    nav_search: "تلاش کریں۔",
    nav_cart: "خریداری کی ٹوکری",
    nav_user_menu: "صارف مینو",
    nav_my_account: "میرا اکاونٹ",
    nav_profile: "پروفائل",
    nav_seller_dashboard: "بیچنے والے کا ڈیش بورڈ",
    nav_store_settings: "اسٹور کی ترتیبات",
    nav_logout: "لاگ آوٹ",
    nav_login: "لاگ ان کریں",
    lang_en: "انگریزی",
    lang_hi: "ہندی",
    lang_ur: "اردو",
    lang_ar: "عربی",
    footer_about: "ہمارے بارے میں",
    footer_contact: "رابطہ کریں۔",
    footer_terms: "سروس کی شرائط",
    footer_privacy: "رازداری کی پالیسی",
    footer_rights: "جملہ حقوق محفوظ ہیں.",
    recommendations_title: "صرف آپ کے لیے",
    featured_products_title: "نمایاں مصنوعات",
    view_all_cta: "سب دیکھیں",
    product_halal_certified: "حلال مصدقہ",
    product_add_to_cart: "ٹوکری میں شامل کریں",
    product_add_to_wishlist: "خواہش کی فہرست میں شامل کرنا",
    product_remove_from_wishlist: "خواہش کی فہرست سے ہٹا دیں۔",
    breadcrumb_home: "گھر",
    about_us_breadcrumb: "ہمارے بارے میں",
    about_our_story_title: "ہماری کہانی",
    about_our_story_desc: "جلال بازار کا জন্ম ایک سادہ خیال سے ہوا: صارفین کو اعلیٰ معیار کی، مستند حلال مصنوعات تلاش کرنے کے لیے ایک قابل اعتماد، خوبصورت اور آسان آن لائن جگہ بنانا۔",
    about_image_alt: "متنوع ٹیم مل کر کام کر رہی ہے۔",
    about_commitment_title: "مستندی اور ایمان کے پابند",
    about_commitment_desc: "ہم سمجھدار صارفین اور اخلاقی فروخت کنندگان کے درمیان فرق کو پر کرتے ہیں جو اپنی حلال مصدقہ پیشکشوں پر فخر کرتے ہیں۔",
    about_mission_title: "ہمارا مقصد",
    about_mission_desc: "ہمارا مشن مسلم صارفین اور کاروباریوں کو بااختیار بنانا ہے۔ ہم ہر فروخت کنندہ اور پروڈکٹ کی باریک بینی سے جانچ پڑتال کرتے ہیں تاکہ یہ یقینی بنایا جا سکے کہ وہ سخت حلال معیارات پر پورا اترتے ہیں، ہر خریداری کے ساتھ ذہنی سکون فراہم کرتے ہیں۔ ہمارا مقصد ایک بازار سے زیادہ ہونا ہے۔ ہم جدید مسلم طرز زندگی کا سنگ بنیاد بننا چاہتے ہیں، اپنی وراثت کا جشن مناتے ہوئے مستقبل کو گلے لگاتے ہیں۔",
    about_vision_title: "ہمارا وژن",
    about_vision_desc: "ہم ایک ایسی دنیا کا تصور کرتے ہیں جہاں ہر مسلمان صارف کو اپنی اقدار کے مطابق مصنوعات تک آسانی سے رسائی حاصل ہو، چاہے وہ کہیں بھی ہوں۔ ہم ایک عالمی برادری کی تعمیر، حلال کاروباروں کے لیے اقتصادی ترقی کو فروغ دینے، اور اعتماد، معیار اور مشترکہ ایمانی اصولوں کا ایک متحرک ماحولیاتی نظام بنانے کی کوشش کرتے ہیں۔",
    cart_breadcrumb: "خریداری کی ٹوکری",
    cart_title: "آپ کی ٹوکری",
    cart_description: "اپنی اشیاء کا جائزہ لیں اور چیک آؤٹ کے لیے آگے بڑھیں۔",
    cart_empty_title: "آپ کی ٹوکری خالی ہے۔",
    cart_empty_desc: "ایسا لگتا ہے کہ آپ نے ابھی تک اپنی ٹوکری میں کچھ شامل نہیں کیا ہے۔",
    cart_start_shopping: "خریداری شروع کریں۔",
    cart_summary_title: "آرڈر کا خلاصہ",
    cart_summary_subtotal: "ذیلی کل",
    cart_summary_shipping: "شپنگ",
    cart_summary_shipping_free: "مفت",
    cart_summary_total: "کل",
    cart_proceed_to_checkout: "چیک آؤٹ کے لیے آگے بڑھیں۔",
    cart_remove_item: "آئٹم کو ہٹا دیں۔",
    breadcrumb_cart: "ٹوکری",
    breadcrumb_checkout: "چیک آؤٹ",
    checkout_title: "چیک آؤٹ",
    checkout_description: "نیچے دی گئی تفصیلات فراہم کرکے اپنی خریداری مکمل کریں۔",
    checkout_form_title: "رابطہ اور شپنگ",
    checkout_form_email: "ای میل اڈریس",
    checkout_form_first_name: "پہلا نام",
    checkout_form_last_name: "آخری نام",
    checkout_form_address: "پتہ",
    checkout_form_city: "شہر",
    checkout_form_country: "ملک",
    checkout_form_postal_code: "ڈاک کوڈ",
    checkout_form_pay: "ادائیگی کریں۔",
    checkout_form_with_razorpay: "Razorpay کے ساتھ",
    checkout_form_processing: "کارروائی ہو رہی ہے...",
    checkout_toast_empty_cart_title: "آپ کی ٹوکری خالی ہے۔",
    checkout_toast_empty_cart_desc: "براہ کرم چیک آؤٹ کرنے سے پہلے اپنی ٹوکری میں اشیاء شامل کریں۔",
    checkout_razorpay_desc: "آپ کی حلال مارکیٹ پلیس کی خریداری",
    checkout_toast_order_placed_title: "آرڈر دے دیا گیا!",
    checkout_toast_order_placed_desc: "آپ کی خریداری کے لئے آپ کا شکریہ. ادائیگی کی شناخت:",
    breadcrumb_contact: "ہم سے رابطہ کریں۔",
    contact_title: "رابطے میں رہنا",
    contact_description: "ہم آپ سے سننا پسند کریں گے۔ چاہے آپ کے پاس ہماری مصنوعات، فروخت کنندگان، یا کسی اور چیز کے بارے میں کوئی سوال ہو، ہماری ٹیم آپ کے تمام سوالات کا جواب دینے کے لیے تیار ہے۔",
    contact_form_first_name: "پہلا نام",
    contact_form_last_name: "آخری نام",
    contact_form_email: "ای میل",
    contact_form_message: "پیغام",
    contact_form_send: "پیغام بھیجیں",
    products_title: "ہمارا مجموعہ",
    products_description: "مستند حلال مصنوعات کے ہمارے منتخب کردہ انتخاب کو دریافت کریں۔",
    products_search_placeholder: "مصنوعات تلاش کریں...",
    products_filter_placeholder: "زمرہ کے لحاظ سے فلٹر کریں۔",
    products_all_categories: "تمام زمرے",
    products_none_found_title: "کوئی پروڈکٹ نہیں ملا",
    products_none_found_desc: "اپنی تلاش یا فلٹرز کو ایڈجسٹ کرنے کی کوشش کریں۔",
    wishlist_title: "خواہش کی فہرست",
    wishlist_description: "آپ کی پسندیدہ اشیاء، سب ایک جگہ پر۔",
    wishlist_empty_title: "آپ کی خواہش کی فہرست خالی ہے۔",
    wishlist_empty_description: "مصنوعات دریافت کریں اور اپنی پسندیدہ چیزیں یہاں شامل کریں۔",
    wishlist_discover_products: "مصنوعات دریافت کریں۔",
  },
  ar: {
    hero_headline: "حيث يلتقي الإيمان بالفخامة",
    hero_subtext: "استكشف سوقًا موثوقًا به للمنتجات الحلال المتميزة - المنسقة بعناية والمتحقق منها بشكل أصلي من أجل راحة بالك وقيمك.",
    hero_cta: "أدخل المجموعة",
    nav_home: "الرئيسية",
    nav_products: "المنتجات",
    nav_about: "معلومات عنا",
    nav_contact: "اتصل",
    nav_admin_dashboard: "لوحة تحكم المسؤول",
    nav_become_seller: "كن بائعا",
    nav_toggle_menu: "تبديل القائمة",
    nav_change_language: "تغيير اللغة",
    nav_search: "بحث",
    nav_cart: "عربة التسوق",
    nav_user_menu: "قائمة المستخدم",
    nav_my_account: "حسابي",
    nav_profile: "الملف الشخصي",
    nav_seller_dashboard: "لوحة تحكم البائع",
    nav_store_settings: "إعدادات المتجر",
    nav_logout: "تسجيل الخروج",
    nav_login: "تسجيل الدخول",
    lang_en: "الإنجليزية",
    lang_hi: "الهندية",
    lang_ur: "الأردية",
    lang_ar: "عربي",
    footer_about: "معلومات عنا",
    footer_contact: "اتصل",
    footer_terms: "شروط الخدمة",
    footer_privacy: "سياسة الخصوصية",
    footer_rights: "كل الحقوق محفوظة.",
    recommendations_title: "فقط لأجلك",
    featured_products_title: "منتجات مميزة",
    view_all_cta: "عرض الكل",
    product_halal_certified: "حلال معتمد",
    product_add_to_cart: "أضف إلى السلة",
    product_add_to_wishlist: "أضف إلى قائمة الامنيات",
    product_remove_from_wishlist: "إزالة من قائمة الرغبات",
    breadcrumb_home: "الرئيسية",
    about_us_breadcrumb: "معلومات عنا",
    about_our_story_title: "قصتنا",
    about_our_story_desc: "وُلد جلال بازار من فكرة بسيطة: إنشاء مساحة إلكترونية موثوقة وأنيقة ومريحة للمستهلكين للعثور على منتجات حلال عالية الجودة وأصلية.",
    about_image_alt: "فريق متنوع يعمل معًا",
    about_commitment_title: "ملتزمون بالأصالة والإيمان",
    about_commitment_desc: "نحن نسد الفجوة بين المستهلكين المميزين والبائعين الأخلاقيين الذين يفخرون بعروضهم المعتمدة كمنتجات حلال.",
    about_mission_title: "مهمتنا",
    about_mission_desc: "مهمتنا هي تمكين المستهلكين ورجال الأعمال المسلمين. نحن نفحص بدقة كل بائع ومنتج للتأكد من استيفائهم لمعايير الحلال الصارمة، مما يوفر راحة البال مع كل عملية شراء. نهدف إلى أن نكون أكثر من مجرد سوق؛ نريد أن نكون حجر الزاوية في نمط الحياة الإسلامي الحديث، نحتفل بتراثنا مع احتضان المستقبل.",
    about_vision_title: "رؤيتنا",
    about_vision_desc: "نتصور عالمًا يتمتع فيه كل مستهلك مسلم بوصول سهل إلى المنتجات التي تتوافق مع قيمه، بغض النظر عن مكان وجوده. نحن نسعى جاهدين لبناء مجتمع عالمي، وتعزيز النمو الاقتصادي للشركات الحلال، وإنشاء نظام بيئي نابض بالحياة من الثقة والجودة والمبادئ المشتركة القائمة على الإيمان.",
    cart_breadcrumb: "عربة التسوق",
    cart_title: "عربة التسوق الخاصة بك",
    cart_description: "راجع أغراضك وتابع عملية الدفع.",
    cart_empty_title: "عربة التسوق فارغة",
    cart_empty_desc: "يبدو أنك لم تضف أي شيء إلى عربة التسوق الخاصة بك بعد.",
    cart_start_shopping: "ابدأ التسوق",
    cart_summary_title: "ملخص الطلب",
    cart_summary_subtotal: "المجموع الفرعي",
    cart_summary_shipping: "شحن",
    cart_summary_shipping_free: "مجانا",
    cart_summary_total: "المجموع",
    cart_proceed_to_checkout: "باشر لإنهاء الدفع",
    cart_remove_item: "إزالة البند",
    breadcrumb_cart: "عربة التسوق",
    breadcrumb_checkout: "الدفع",
    checkout_title: "الدفع",
    checkout_description: "أكمل عملية الشراء من خلال تقديم التفاصيل أدناه.",
    checkout_form_title: "الاتصال والشحن",
    checkout_form_email: "عنوان البريد الإلكتروني",
    checkout_form_first_name: "الاسم الأول",
    checkout_form_last_name: "اسم العائلة",
    checkout_form_address: "عنوان",
    checkout_form_city: "مدينة",
    checkout_form_country: "دولة",
    checkout_form_postal_code: "الرمز البريدي",
    checkout_form_pay: "ادفع",
    checkout_form_with_razorpay: "مع ريزورباي",
    checkout_form_processing: "معالجة...",
    checkout_toast_empty_cart_title: "عربة التسوق فارغة",
    checkout_toast_empty_cart_desc: "يرجى إضافة عناصر إلى سلة التسوق الخاصة بك قبل الخروج.",
    checkout_razorpay_desc: "شراء سوق الحلال الخاص بك",
    checkout_toast_order_placed_title: "تم الطلب!",
    checkout_toast_order_placed_desc: "شكرا لك على الشراء. معرف الدفع:",
    breadcrumb_contact: "اتصل بنا",
    contact_title: "ابقى على تواصل",
    contact_description: "يسعدنا أن نسمع منك. سواء كان لديك سؤال حول منتجاتنا أو البائعين أو أي شيء آخر ، فإن فريقنا مستعد للإجابة على جميع أسئلتك.",
    contact_form_first_name: "الاسم الأول",
    contact_form_last_name: "اسم العائلة",
    contact_form_email: "البريد الإلكتروني",
    contact_form_message: "رسالة",
    contact_form_send: "إرسال رسالة",
    products_title: "مجموعتنا",
    products_description: "اكتشف مجموعتنا المختارة من المنتجات الحلال الأصيلة.",
    products_search_placeholder: "البحث عن المنتجات...",
    products_filter_placeholder: "التصفية حسب الفئة",
    products_all_categories: "جميع الفئات",
    products_none_found_title: "لم يتم العثور على منتجات",
    products_none_found_desc: "حاول تعديل البحث أو المرشحات.",
    wishlist_title: "قائمة الرغبات",
    wishlist_description: "العناصر المفضلة لديك ، كلها في مكان واحد.",
    wishlist_empty_title: "قائمة أمنياتك فارغة",
    wishlist_empty_description: "اكتشف المنتجات وأضف مفضلاتك هنا.",
    wishlist_discover_products: "اكتشف المنتجات",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
    const storedLang = localStorage.getItem("jalal-language") as Language | null;
    if (storedLang && translations[storedLang]) {
      setLanguageState(storedLang);
    }
  }, []);

  useEffect(() => {
      if (isMounted) {
        document.documentElement.lang = language;
        document.documentElement.dir = (language === 'ar' || language === 'ur') ? 'rtl' : 'ltr';
      }
  }, [language, isMounted]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if(isMounted) {
        localStorage.setItem("jalal-language", lang);
    }
  };

  const t = useCallback((key: string): string => {
    return translations[language]?.[key] || translations['en'][key] || key;
  }, [language]);


  const value = {
    language,
    setLanguage,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
